### ISSUE TITLE
v1.10.1 crashes with java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by leandrotlz** [mircokroon/minecraft-world-downloader#107]
**Describe the bug**

World Downloader starts fine and displays the name of the server on the Multiplayer screen; however, as soon as the connection is established, it crashes during the "Encryption" screen, with the error message below.

Running the vanilla client with no mods results in the same issue.

Tested on multiple servers, including my own running Paper #449.

**Steps to reproduce**

Start World Downloader with the following settings: "C:\Program Files (x86)\Minecraft\runtime\jre-x64\bin\java.exe" -jar world-downloader.jar --output output --server server --render-distance 18

Try to join any servers; I don't want to disclose my own server's address, but beardcraft.us and mc.minehut.com will display the same error.

**Log output**
```
Exception in thread "Thread-5" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at packets.DataTypeProvider.readLong(DataTypeProvider.java:139)
        at packets.DataTypeProvider.readUUID(DataTypeProvider.java:198)
        at packets.handler.ClientBoundLoginPacketHandler.lambda$new$2(ClientBoundLoginPacketHandler.java:33)
        at packets.handler.ClientBoundLoginPacketHandler$$Lambda$142/1002433498.apply(Unknown Source)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:104)
        at proxy.ProxyServer$$Lambda$126/909157587.run(Unknown Source)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:101)
        at proxy.ProxyServer$$Lambda$98/994518778.run(Unknown Source)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:60)
```

**Version**
 - Game: Minecraft 1.16.5
 - Downloader: latest

**Comment by leandrotlz** [comment]
**Solved**: World Downloader doesn't work with the Java runtime included with Minecraft. Counter-intuitive, but not a big deal. Installed `Java (AdoptOpenJDK) x64 11` from [www.ninite.com](www.ninite.com) and started the program with `"C:\Program Files\AdoptOpenJDK\jre-11.0.7.10-hotspot\bin\java.exe" -jar world-downloader.jar --output output --server server --render-distance 18` and it is now working.

**Suggestion**: make a note in the README that the included JRE is not compatible and AdoptOpenJDK should be used instead.

**Comment by mircokroon** [comment]
Actually this seemed to be a weird difference between Java 8 and Java 9, while it compiles on both it does something different at runtime. Fixed now, thanks!
