### ISSUE TITLE
Lost compatibility with Java runtime bundled with Minecraft and basic AdoptOpenJDK installs

### ISSUE THREAD

**Issue by leandrotlz** [mircokroon/minecraft-world-downloader#117]
**Describe the bug**
The latest release seems to be using a newer version of JavaFX than supported by the Java runtime bundled in Minecraft and AdoptOpenJDK. Attempting to start the jar using either of those fails to open the main preview window; the settings window still works fine.

**Note:** the .exe version works fine on the same system with no extra downloads. I am not a Java developer so I have no idea where is it pulling dependencies from.

**Steps to reproduce**
Run the .jar using either the Java runtime built-in with Minecraft:

```
"C:\Program Files (x86)\Minecraft\runtime\jre-x64\bin\javaw.exe" -jar world-downloader.jar
```

This results in the screenshot below when clicking Start on the settings window.

![image](https://user-images.githubusercontent.com/3232902/108266317-b7ca3b00-7148-11eb-860d-aa51b8742733.png)

Attempt to run the .jar using the AdoptOpenJDK 11 runtime:

```
"D:\Program Files\AdoptOpenJDK\jdk-11.0.3.7-hotspot\bin\java.exe" -jar world-downloader.jar
```

This results in the following error log:

```
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "Thread-0" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Version**
 - Downloader: 1.11.3

**Comment by mircokroon** [comment]
Getting JavaFX to run on all versions is a massive pain, since it used to be bundled with Java but isn't anymore. It needs to be packed into the Jar for newer versions, but Java 8 (which Minecraft uses) refuses to use the bundled one and uses the internal JavaFX instead. I must have already ran into this same issue like 5 times before (and fixed those). 

I guess I should set up some GUI tests on multiple versions. Thanks for the report, I'll see if I can fix at least the first one.

The second issue seems to be related to having the wrong version of OpenJDK set up, see here: https://stackoverflow.com/a/57909630/14192293

**Comment by leandrotlz** [comment]
Installed OpenJDK12U-jdk_x64_windows_hotspot_12.0.2_10.msi and ran the jar with it -- same issue. I found this information in the [AdoptOpenJDK FAQ](https://adoptopenjdk.net/faq.html): _Up until JDK 10, JavaFX was a part of the JDK. In 2018, Oracle decided to decouple JavaFX from the JDK. JavaFX lives on as OpenJFX, an OpenJDK subproject. As JavaFX is no longer part of OpenJDK, AdoptOpenJDK does not bundle it with its binaries._ So I'm going to see about installing OpenJFX and test with that.

```
"D:\Program Files\AdoptOpenJDK\jdk-12.0.2.10-hotspot\bin\java.exe" -jar world-downloader.jar
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "Thread-0" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by mircokroon** [comment]
Indeed, but JavaFX is bundled in the .jar file so it is *supposed* to work. I am able to run it with both standalone Java 8 and Java 15 (where 8 uses internal and 15 uses bundles JavaFX). I'll try to understand this issue better tomorrow.

**Comment by leandrotlz** [comment]
Okay, since you mentioned Java 15 I went ahead and downloaded the OpenJDK 15 runtime openjdk-15.0.2_windows-x64_bin.zip from https://jdk.java.net/15/ and tried to run the jar with it. No joy:

```
"D:\Program Files\jdk-15.0.2\bin\java.exe" -jar world-downloader.jar
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "Thread-0" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by mircokroon** [comment]
I have at least fixed the Java 8 problem (again). If the method it complained about isn't found it'll fail silently, the effect of this is that the image is not rendered very nicely. 

As a comparison, here is a Java 9+:
![image](https://user-images.githubusercontent.com/23699979/108341862-6c606d00-71da-11eb-9617-bef7f81ce10c.png)
And Java 8:
![image](https://user-images.githubusercontent.com/23699979/108341922-7b471f80-71da-11eb-8724-8eab8be0f322.png)

It's *fine*, a bit unfortunate there isn't a straightforward easier solution.

**Comment by mircokroon** [comment]
And I fixed the other issue too! The output .jar file was being minimized (since JavaFX increased the size drastically, which I tried to remedy a bit) and it was accidentally getting rid of a few JavaFX required parts. I added a filter for them now and it works with OpenJDK for me.

**Comment by mircokroon** [comment]
Let me know if there's still issues in the latest release, hopefully this solves most of the annoying stuff.

**Comment by leandrotlz** [comment]
I can confirm that world-downloader.jar is now launching correctly with the built-in Minecraft runtime as well as OpenJDK 15.0.2 and AdoptOpenJDK 11.0.10.9 - nice job.
