### ISSUE TITLE
Authentication does not work with Microsoft (migrated) accounts

### ISSUE THREAD

**Issue by wendellmeset** [mircokroon/minecraft-world-downloader#143]
So i dont understand, can you please make a video tutorial using hypixel as an example, please and thank you! (also im using ATLauncer, a premium minecraft modpack launcher, you can get it here: https://atlauncher.com/  )

I did everything you said and im getting this error:

```
**javax.security.sasl.AuthenticationException: Invalid access token length! Expected 308, found 331
	at proxy.auth.AuthDetails.fromUsername(AuthDetails.java:45)
	at config.Config.getManualAuthDetails(Config.java:446)
	at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:91)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:31)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$null$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$null$6(ProxyServer.java:83)
	at java.lang.Thread.run(Thread.java:748)
Something went wrong while trying to authenticate your Minecraft account.

Set the correct Minecraft installation path in the Connection tab.
If you are using a custom launcher, set the correct username and token in the authentication tab.
See https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication for more details.

javax.security.sasl.AuthenticationException: Cannot get valid authentication details. [Caused by java.nio.file.NoSuchFileException: %appdata%\.minecraft\launcher_profiles.json]
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:34)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$null$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$null$6(ProxyServer.java:83)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: %appdata%\.minecraft\launcher_profiles.json
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.readAllLines(Files.java:3202)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at proxy.auth.AuthDetailsManager.readProfiles(AuthDetailsManager.java:77)
	at proxy.auth.AuthDetailsManager.retrieveAuthDetails(AuthDetailsManager.java:42)
	at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:98)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:31)
	... 14 more
java.lang.IllegalStateException: Packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
	at packets.DataReader.readPackets(DataReader.java:172)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$null$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$null$6(ProxyServer.java:83)
	at java.lang.Thread.run(Thread.java:748)**
```

**Comment by Qwertylex** [comment]
In that log you pasted... did you happen to notice the part that says:

```
Something went wrong while trying to authenticate your Minecraft account.

Set the correct Minecraft installation path in the Connection tab.
If you are using a custom launcher, set the correct username and token in the authentication tab.
See https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication for more details.
```
You probably have to set the "minecraft location" box to wherever your ATLauncher thingy put it.
If that doesn't help, you may have to manually feed the downloader your token. See that wiki page for more details.
Again: https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication

**Comment by mircokroon** [comment]
I'm also seeing `Invalid access token length! Expected 308, found 331`, so perhaps you tried to set the access token but copied too much by accident?

**Comment by wendellmeset** [comment]
Hey @mircokroon @Qwertylex so i have to say, I have no idea how on earth I get my access token from ATLauncher, so thats what i mainly need help with.

**Comment by mircokroon** [comment]
I had a look around and it seems to be stored in `configs/accounts.json` in the installation directory of the launcher. The structure of the file is similar to the example on the wiki page.

**Comment by wendellmeset** [comment]
@mircokroon So i tried that, and it turns out, its 349 characters, the structure looks like this:
`"accessToken": "My 349 Character Access Token"`

**Comment by wendellmeset** [comment]
And i searched allll over and cant find a 308 Character Access token

**Comment by mircokroon** [comment]
Hmm I've not seen any access tokens longer than 308. The line is 331 characters for me if I also copy the `"accessToken": ` part, but the GUI should filter that out so it's probably a coincidence.

I made a pre-release that allows different lengths of accessTokens, can you connect with this? 
https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.13.5

**Comment by wendellmeset** [comment]
Now im  getting a error that means it cant authenticate @mircokroon

**Comment by mircokroon** [comment]
Do you have multiple accounts? If so, you may be using the wrong token

**Comment by wendellmeset** [comment]
I only have 1 account on AtLauncher @mircokroon

**Comment by wendellmeset** [comment]
**Heres how my accounts.json looks like:
```
[
  {
    "accessToken": "a token",
    "oauthToken": {
      "token_type": "bearer",
      "expires_in": 3600,
      "expires_at": "a date",
      "scope": "XboxLive.signin XboxLive.offline_access",
      "access_token": "a super longer token thats like 2000 characters",
      "refresh_token": "another too long token",
      "user_id": "my user id"
    },
    "xstsAuth": {
      "IssueInstant": "a date",
      "NotAfter": "a date",
      "Token": "another super dupe long token",
      "DisplayClaims": {
        "xui": [
          {
            "uhs": "my uhs"
          }
        ]
      }
    },
    "accessTokenExpiresAt": "a date",
    "mustLogin": false,
    "username": "my username id",
    "minecraftUsername": "wendellmeset",
    "uuid": "my uuid",
    "type": "Xbox",
    "collapsedPacks": [],
    "collapsedInstances": [],
    "collapsedServers": [],
    "skinUpdating": true,
    "internalType": "com.atlauncher.data.MicrosoftAccount"
  }
]
```

**Comment by mircokroon** [comment]
Hmmm this is a Microsoft account instead of a Mojang one, thats probably the issue. I'm not sure how these are any different from Mojang auth tokens and if this requires some special handling or not.

**Comment by wendellmeset** [comment]
Please oh please make it work with microsoft accounts!
I really want this to work, no pressure, i just love how this looks and the reason that it works with any client makes me like it even more!

**Comment by mircokroon** [comment]
I'd like to, but I don't have access to any Microsoft accounts to test this with. I'll be able to do it when they start allowing Microsoft account migrations at least, until then it would be quite difficult.

**Comment by Qwertylex** [comment]
unless you buy a new minecraft licence or someone donates minecraft gift code to you ..
(all new minecraft purchases are microsoft'd)

**Comment by mircokroon** [comment]
That is true, but I imagine they should start the migration pretty soon anyway

**Comment by wafflecoffee** [comment]
Just to let you know of this if you didn't already know about it:
https://wiki.vg/Microsoft_Authentication_Scheme

**Comment by mircokroon** [comment]
That's good but there's no way for me to verify that any of the implementation actually works without an account to test it with

**Comment by heinGertenbach** [comment]
Since Microsoft account migrations have slowly started will there be development to support them any time soon?

**Comment by mircokroon** [comment]
Yup, once either account I own gets migrated I'll probably get it done in a few days. So far it seems they are only allowing a small number of accounts to migrate though.

**Comment by wendellmeset** [comment]
hi, im just wondering if you made it work for Microsoft accounts yet, also I can test it or you if your just looking for an account to test with

**Comment by mircokroon** [comment]
I might have fixed this by accident by changing how access tokens are retrieved (for #180). Can someone with a Microsoft account see how it goes on this release?
https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.14.3

**Comment by mircokroon** [comment]
@wendellmeset seems to be working now sort of coincidentally, confirmed by someone with a Microsoft account in #180. If any issues pop up, feel free to let me know.
