### ISSUE TITLE
Attempting to download section of map results in `java.lang.UnsupportedOperationException` error. All chunks loaded after stay red in GUI. Don't save upon exit.

### ISSUE THREAD

**Issue by ASchneider-GitHub** [mircokroon/minecraft-world-downloader#148]
This just recently started happening with the latest .jar release of the program. I switched away from the .exe version because it was running out of memory, and the Java flags let me dedicate 8GB of memory to the program (`java -Xmx8192m -jar world-downloader.jar`)

Currently when trying to download the part of the map that I load when I log in, the chunks in the GUI turn red and stay that way. When I re-log, the chunks that were red are no longer shown as downloaded in the GUI. The command prompt session throws the following error.

```
java.lang.UnsupportedOperationException
        at java.base/java.util.AbstractMap.put(Unknown Source)
        at game.data.region.McaFile.lambda$addChunks$4(McaFile.java:244)
        at java.base/java.util.HashMap.forEach(Unknown Source)
        at game.data.region.McaFile.addChunks(McaFile.java:244)
        at game.data.region.Region.toFile(Region.java:164)
        at game.data.WorldManager.save(WorldManager.java:424)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
        at game.data.WorldManager.lambda$start$2(WorldManager.java:401)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Is there something I'm doing incorrectly that's causing it to throw this error? How can I go about fixing it? Attached is a screenshot of what's shown in the GUI when the issue presents.
![Screenshot_1](https://user-images.githubusercontent.com/65742424/113942148-3b9dbc80-97b5-11eb-98c0-ad3d5e00eaa2.png)

**Comment by mircokroon** [comment]
I think I found the issue, it seems that when a region is saved without chunks it can't add new ones to it. 

As for the memory limit, I guess there needs to be some automatic unloading of the overview chunks when the memory is near it's limit. I opened a separate issue for that.

**Comment by ASchneider-GitHub** [comment]
Incredible turn around time on the patch. Thank you so much!
