### ISSUE TITLE
Using "Draw Nearby Existing Chunks" option on map eventually throws Java NPE

### ISSUE THREAD

**Issue by ASchneider-GitHub** [mircokroon/minecraft-world-downloader#151]
**Describe the bug**
Attempting to use the "Draw Nearby Existing Chunks" on decently large map results in console throwing Java NPE ; Downloader becomes unresponsive and has to be force-closed.

**Jar launch command**
`java -Xmx16384m -jar world-downloader.jar --measure-render-distance --extended-render-distance 16 --server [server hostname]`

**Log output**
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at gui.GuiMap.drawChunk(GuiMap.java:615)
        at gui.GuiMap.drawChunk(GuiMap.java:606)
        at gui.GuiMap.redrawCanvas(GuiMap.java:509)
        at gui.GuiMap.computeBounds(GuiMap.java:497)
        at gui.GuiMap.lambda$setupCanvasProperties$7(GuiMap.java:249)
        at javafx.graphics/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
        at javafx.graphics/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
        at javafx.graphics/javafx.animation.Timeline.doPlayTo(Unknown Source)
        at javafx.graphics/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
        at javafx.graphics/com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(Unknown Source)
        at javafx.graphics/javafx.animation.Animation.doTimePulse(Unknown Source)
        at javafx.graphics/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/javafx.animation.Animation$1.timePulse(Unknown Source)
        at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(Unknown Source)
        at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Version**
 - Game: Minecraft 1.16.5
 - Downloader: Latest JAR file

**Comment by mircokroon** [comment]
Not sure what caused this but I just added a check for it to at least prevent problems when it occurs
