### ISSUE TITLE
Unable to run GUI on Ubuntu 20.04

### ISSUE THREAD

**Issue by DoctorSnakes** [mircokroon/minecraft-world-downloader#162]
**Describe the bug**
I downloaded this with the instructions provided in the readme, but when I try launching the GUI through the terminal I get the error below. Am I missing some kind of package?

**Log output**
```
java.lang.ClassNotFoundException: com.sun.glass.ui.gtk.GtkPlatformFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)
Failed to load Glass factory class
Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.PlatformFactory.createApplication()" because the return value of "com.sun.glass.ui.PlatformFactory.getPlatformFactory()" is null
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:280)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)

```

**Version**
 - Game: Minecraft 1.16.5
 - Downloader: latest

**Comment by mircokroon** [comment]
Is it able to load if you disable the GUI with `--no-gui`? I think you might be missing some sort of JavaFX dependency but I'm not sure, you may be able to install it somehow

**Comment by DoctorSnakes** [comment]
> Is it able to load if you disable the GUI with `--no-gui`? I think you might be missing some sort of JavaFX dependency but I'm not sure, you may be able to install it somehow

It seems to work fine without using the GUI, so yeah it is a problem with the GUI. What JavaFX dependency could I be missing?

**Comment by mircokroon** [comment]
I think it might be this: https://askubuntu.com/a/1091162

I'm not 100% sure since I think usually it gives a different error message, but it's worth trying at least.

**Comment by DoctorSnakes** [comment]
> I think it might be this: https://askubuntu.com/a/1091162
> 
> I'm not 100% sure since I think usually it gives a different error message, but it's worth trying at least.

Tried it, but I still get the same error.

**Comment by mircokroon** [comment]
What version/type of Java are you using?

**Comment by DoctorSnakes** [comment]
> What version/type of Java are you using?

Output of `java -version` in the terminal:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)

```

**Comment by DoctorSnakes** [comment]
Also here is the output when I run it with the `-verbose` option, maybe the added information could help.

[verbose.txt](https://github.com/mircokroon/minecraft-world-downloader/files/6600681/verbose.txt)

**Comment by mircokroon** [comment]
It's possible there's some files missing in the compilation, I'll look into that tomorrow

**Comment by mircokroon** [comment]
I would suggest trying to install a different Java version actually. I'm not really able to find anything that could fix this.

**Comment by mircokroon** [comment]
Should be fixed now I think, you may need to use `-Djdk.gtk.version=2` as a launch option as well
