### ISSUE TITLE
Invalid Access token length error

### ISSUE THREAD

**Issue by heinGertenbach** [mircokroon/minecraft-world-downloader#171]
I use ATLauncher with a Mojang account I set up the path to the folder containing the auth.json file. It recognises the token but it is too long? I see no obvious deliminators in the token.

**Log output**
```
javax.security.sasl.AuthenticationException: Invalid access token length! Expected 308, found 312
        at proxy.auth.AuthDetails.fromUsername(AuthDetails.java:45)
        at config.Config.getManualAuthDetails(Config.java:445)
        at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:91)
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:31)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:831)
Something went wrong while trying to authenticate your Minecraft account.
```

**Version**
 - Game: Minecraft 1.17

**Comment by heinGertenbach** [comment]
I saw the issue on: Authentication does not work with Microsoft (migrated) accounts #143
