### ISSUE TITLE
Can't download some chunks

### ISSUE THREAD

**Issue by katant** [mircokroon/minecraft-world-downloader#172]
**Describe the bug**
I've tried to download vanila 1.15.2 world, but there is missings chunks everytime (and they are same!). Other tool can download only 50% of that chunks, so it may be issue with server?

**Steps to reproduce**
Join server and look at map.

**Log output**
```
Exception in thread "Chunk Parser Service" Exception in thread "Chunk Parser Service" java.lang.NullPointerException: Cannot read the array length because "this.palette" is null
        at game.data.chunk.palette.Palette.getIndexFor(Palette.java:170)
        at game.data.chunk.ChunkSection.setBlockAt(ChunkSection.java:154)
        at game.data.chunk.Chunk.updateBlock(Chunk.java:483)
        at game.data.chunk.Chunk.updateBlock(Chunk.java:469)
        at game.data.WorldManager.lambda$blockChange$5(WorldManager.java:661)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Exception in thread "Chunk Parser Service" java.lang.NullPointerException: Cannot read the array length because "this.palette" is null
        at game.data.chunk.palette.Palette.getIndexFor(Palette.java:170)
        at game.data.chunk.ChunkSection.setBlockAt(ChunkSection.java:154)
        at game.data.chunk.Chunk.updateBlock(Chunk.java:483)
        at game.data.chunk.Chunk.updateBlocks(Chunk.java:514)
        at game.data.WorldManager.lambda$multiBlockChange$6(WorldManager.java:675)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
        
        
 java.lang.UnsupportedOperationException: Cannot convert a dummy palette to NBT
        at game.data.chunk.palette.DummyPalette.toNbt(DummyPalette.java:31)
        at game.data.chunk.version.ChunkSection_1_13.createPalette(ChunkSection_1_13.java:60)
        at game.data.chunk.version.ChunkSection_1_13.addNbtTags(ChunkSection_1_13.java:56)
        at game.data.chunk.ChunkSection.toNbt(ChunkSection.java:74)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at game.data.chunk.Chunk.getSectionList(Chunk.java:244)
        at game.data.chunk.Chunk.addLevelNbtTags(Chunk.java:233)
        at game.data.chunk.version.Chunk_1_13.addLevelNbtTags(Chunk_1_13.java:61)
        at game.data.chunk.version.Chunk_1_14.addLevelNbtTags(Chunk_1_14.java:40)
        at game.data.chunk.Chunk.createNbtLevel(Chunk.java:214)
        at game.data.chunk.Chunk.toNbt(Chunk.java:197)
        at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:91)
        at game.data.region.Region.lambda$toFile$0(Region.java:142)
        at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
        at game.data.region.Region.toFile(Region.java:123)
        at game.data.WorldManager.save(WorldManager.java:426)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
        at game.data.WorldManager.lambda$start$2(WorldManager.java:403)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```
**Screenshots**
![image](https://user-images.githubusercontent.com/9751407/123775904-75bfbb80-d8d7-11eb-865b-f01d5b1947bd.png)
![image](https://user-images.githubusercontent.com/9751407/123776575-1615e000-d8d8-11eb-9d22-7f0093a03648.png)

**Version**
 - Game: Minecraft 1.15.2
 - Downloader: latest, compiled from source

**Comment by mircokroon** [comment]
I think these chunks most likely contain sections with more than 256 different blocks (or if they don't, the server might be modified in some way to send them as if they do have more blocks). I was able to reproduce the at least some of the error by doing that.

**Comment by katant** [comment]
I don't think that this is main reason for my case, maybe only for that two chunk standing side by side. There is also one clean chunk, that doesn't even have chests in it. For them I have "Unable to save inventory at ... No block found."
As for me, main goal is to download all chunks, except the mentioned two chunks (I don't care about them).

**Comment by katant** [comment]
Checked your  updated version and it works. So I think this is fixed.
