### ISSUE TITLE
World save stops after java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by katant** [mircokroon/minecraft-world-downloader#174]
**Describe the bug**
World save stops after java.util.ConcurrentModificationException, only one instance of app is running.

**Steps to reproduce**
Starts from world size of +1Gb, after some saved chunks. App reload fixes it, but chunks that aren't saved are lost. Possibly due to low write speed? 

**Log output**
```
java.util.ConcurrentModificationException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1584)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1607)
        at game.data.region.Region.toFile(Region.java:162)
        at game.data.WorldManager.save(WorldManager.java:426)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
        at game.data.WorldManager.lambda$start$2(WorldManager.java:403)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Version**
 - Game: Minecraft 1.15.2
 - Downloader: latest, compiled from source

**Comment by mircokroon** [comment]
I guess this was just caused by some unfortunate thread timing, should pretty easy to fix

**Comment by mircokroon** [comment]
Actually, did this happen consistently or was it just a one-off?

**Comment by katant** [comment]
It happened 3 times for me

**Comment by mircokroon** [comment]
Weird, well let me know if it happens any more on that commit

**Comment by katant** [comment]
Not related to this issue, but there is also issue with map overview render, the map is circle, but I get only quarter of the map
![image](https://user-images.githubusercontent.com/9751407/123863071-a3792480-d918-11eb-8d42-93b027911479.png)

**Comment by katant** [comment]
Downloaded other part of map, not happened again. I think this is fixed.

**Comment by mircokroon** [comment]
Great. The map thing is for performance reasons mostly, it eats up a fair bit of RAM to load so many chunk positions, some optimization is needed there.
