### ISSUE TITLE
Error when trying to open chests or any other container on 1.17.1

### ISSUE THREAD

**Issue by krivoruk420** [mircokroon/minecraft-world-downloader#176]
**Describe the bug**
Error when trying to open chests or any other container on 1.17.1

**Steps to reproduce**
Opening any container on 1.17.1 causes an error. Also opened chests and inventory are not saving. 
**Log output**
```
java.lang.ArrayIndexOutOfBoundsException: Index 156034 out of bounds for length 156034
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readBoolean(DataTypeProvider.java:97)
	at packets.version.DataTypeProvider_1_13.readSlot(DataTypeProvider_1_13.java:21)
	at packets.DataTypeProvider.readSlots(DataTypeProvider.java:234)
	at game.data.container.ContainerManager.items(ContainerManager.java:172)
	at packets.handler.ClientBoundGamePacketHandler.lambda$new$20(ClientBoundGamePacketHandler.java:157)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)


```
**Screenshots**
![image](https://user-images.githubusercontent.com/79770981/125142276-068c6780-e120-11eb-9d3e-40f189838433.png)
![image](https://user-images.githubusercontent.com/79770981/125142338-2885ea00-e120-11eb-9f27-1bf5570ea409.png)
![image](https://user-images.githubusercontent.com/79770981/125142365-363b6f80-e120-11eb-8e93-8bca7308659d.png)
![image](https://user-images.githubusercontent.com/79770981/125142381-43f0f500-e120-11eb-9add-8ed7d87ff442.png)

**Version**
 - Game: Minecraft 1.17.1
 - Downloader: latest

**Comment by mircokroon** [comment]
Thanks for the report! Should be fixed soon.
