### ISSUE TITLE
Realms 400 Bad Request

### ISSUE THREAD

**Issue by brightcuttlefish** [mircokroon/minecraft-world-downloader#179]
**Describe the bug**
Downloader cannot request Realms seemingly due to malformed requests. As a result, the addresses of Realms the player has access to cannot be viewed, instead producing an error output and returning "No realms found for user ASDF" (for some user ASDF).

**Steps to reproduce**
Launch world-downloader.exe, click on the "Realms" tab of the GUI

**Log output**
```
proxy.auth.RealmsApiHandler$RealmsRequestException: Could not request realms. Reason: 400 - Bad Request (body: )
	at proxy.auth.RealmsApiHandler.lambda$realmRequest$2(RealmsApiHandler.java:39)
	at kong.unirest.CallbackFuture$1.complete(CallbackFuture.java:36)
	at kong.unirest.CallbackFuture$1.complete(CallbackFuture.java:33)
	at kong.unirest.apache.ApacheAsyncClient$1.completed(ApacheAsyncClient.java:183)
	at kong.unirest.apache.ApacheAsyncClient$1.completed(ApacheAsyncClient.java:176)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(Unknown Source)       
```

**Version**
 - Game: Minecraft 1.17.0
 - Downloader: latest release, Windows executable
 - Launcher: 2.2.3555 (updated 7/12/2021)

**Comment by mircokroon** [comment]
I'm not 100% sure but this might be caused by #180

**Comment by mircokroon** [comment]
Can you see if this issue still occurs on the pre-release version? https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.14.3
