### ISSUE TITLE
How To Install?

### ISSUE THREAD

**Issue by CoderA07** [mircokroon/minecraft-world-downloader#18]
Help me with how to install. I got error to. and How to install Java 9 ?

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by ChillerDragon** [comment]
Why java 9? What is your current java version? For me it worked fine on debian using openjdk 13.
```
$ java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```

In case you want to build it these steps worked for me (from the readme):

```
$ git clone https://github.com/mircokroon/minecraft-world-downloader
$ cd minecraft-world-downloader
$ mvn assembly:assembly
$ java -jar ./target/world-downloader.jar -s address.to.server.com
```

But seems like you just wanted to download the release and run it. In this case I recommend you to update your java. Depending on what operating system you are on and where you got your current version. Maybe https://java.com/en/download/ is worth a try.

**Comment by 8bit-coder** [comment]
Hmmm, I've gone down the same rabbit hole. I got the same exact error, even though I just went to the java website ChillerDragon linked, downloaded the latest version, fixed the PATH variable, and restarted my computer. I'm currently trying to get mvn working to try and compile it myself.

**Comment by ChillerDragon** [comment]
> Hmmm, I've gone down the same rabbit hole. I got the same exact error, even though I just went to the java website ChillerDragon linked, downloaded the latest version, fixed the PATH variable, and restarted my computer. I'm currently trying to get mvn working to try and compile it myself.

@8bit-coder if your java version is too old building from source wont work either. What do you get when executing ``java --version`` ?
