### ISSUE TITLE
Client not authenticated!

### ISSUE THREAD

**Issue by 2fncool** [mircokroon/minecraft-world-downloader#180]
Attempting to connect now results in the following even though I've successfully used the world downloader many times before.  I'm using the vanilla launcher.  The lines for my accessToken in launcher_accounts.json say:
    "accessToken" : "",
I do not know where else my access token would reside so I am not able to use manual authentication.  Problem happens with multiple servers which I can connect to when choosing them directly.  I had the problem with a previously working version of world-downloader.jar.  I have the same problem with the latest version of world-downloader.jar and world-downloader.exe on Windows 10.

Please help.

![image](https://user-images.githubusercontent.com/87552213/126019717-08a094f7-b91a-43b3-94fd-e3eeb214f983.png)

java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:54)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:831)
Server probably disconnected. Waiting for new connection...
Client probably disconnected. Waiting for new connection...

**Comment by 2fncool** [comment]
I was able to connect to a server via world-downloader.exe using the following work-around.  I logged in to my account using 1.16.4 in MultiMC.  I don't know if the Minecraft version matters.  MultiMC wrote my accessToken to MultiMC/accounts.json.  I copied the accessToken from MultiMC/accounts.json to the Authentication tab of world-downloader.exe, quit MultiMC, launched my vanilla launcher and connected via world-downloader.exe as usual.  I still don't know where the standard launcher is keeping the access token.

**Comment by mircokroon** [comment]
Hmm yeah it looks like the latest launcher version changed the authentication (again), I'll see if it can be fixed

**Comment by 2fncool** [comment]
Thank you for looking in to this.  Oddly, automatic authentication is working today, at least with my Mojang account.  I could not authenticate with my Microsoft account, but that does not surprise me.

**Comment by mircokroon** [comment]
I guess you can't exactly test it if it works again, but I think this should fix it: https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.14.3

**Comment by 2fncool** [comment]
Thank you for the new version.  That also works with my Mojang account and not my Microsoft account:

Microsoft account:
Server probably disconnected. Waiting for new connection...
WARNING: Connection attempt by using pretending to be you! Closing connection.
java.lang.RuntimeException: Server could not authenticate client! {}
        at proxy.auth.ServerAuthenticator.makeRequest(ServerAuthenticator.java:33)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$7(EncryptionManager.java:229)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:229)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:831)
Client probably disconnected. Waiting for new connection...
Server probably disconnected. Waiting for new connection...
Server probably disconnected. Waiting for new connection...

Mojang account:
Login success: Dern_Fool_Idjit logged in with uuid <redacted>
Using protocol of game version 1.16.2 (754)

**Comment by lenzls** [comment]
This fixed the issue for me. Thanks for the quick response and fix!

**Comment by mircokroon** [comment]
Hmm the Microsoft account gives a warning that happens when there is some mismatch with accounts, can you double check that it always happens and wasn't just some mixup with your two accounts?

**Comment by WolfGames** [comment]
proxy.auth.RealmsApiHandler$RealmsRequestException: Could not request realms. Reason: 401 - Unauthorized (body: )

**Comment by 2fncool** [comment]
> Hmm the Microsoft account gives a warning that happens when there is some mismatch with accounts, can you double check that it always happens and wasn't just some mixup with your two accounts?

I don't understand how, but world-downloader.jar was using the access token I put in to world-downloader.exe yesterday.  That is why world-downloader.jar was working this morning.  I removed the access token from world-downloader.exe and can now connect with my Mojang and Microsoft accounts automatically using the version of world-downloader.exe you gave me today.  Thank you for the new version and quick response.  You are a legend!

**Comment by mircokroon** [comment]
Ah yeah they both use the same config file, so that might be why. Great to hear that it's working well now!
