### ISSUE TITLE
Windows executable Java version issue

### ISSUE THREAD

**Issue by brightcuttlefish** [mircokroon/minecraft-world-downloader#183]
**Describe the bug**
Upon loading into localhost, WDL produces an error which states that Minecraft's Java version is incorrect (version 8 when 16 is required).  WDL then repeatedly produces a chunk parsing error in the log due to this version mismatch. The connection to the server is still maintained, but WDL is not functional.

Strangely enough, Minecraft is running Java 16 (by manually setting the Java executable location). Uninstalling Java 8 entirely from the system prevents WDL from running (requires Java 8), though Minecraft can still run. The Java version on the Windows Path environment variable is Java 16.

In addition, this error seems to happen only with the Windows executable - using the JAR file from the command line works as intended.

**Steps to reproduce**
Launch world-downloader.exe, search and select Realm, start connection to server, then connect to localhost

**Log output**
```
Cannot run Minecraft version 1.17+ with a Java version below 16. You are currently using Java version 8.
Please consider upgrading your Java version to at least version 16.

game.UnsupportedMinecraftVersionException: Minecraft version 1.17 is not supported for java version 8
	at game.data.registries.RegistryLoader.getReportsFromServerJar(RegistryLoader.java:115)
	at game.data.registries.RegistryLoader.<init>(RegistryLoader.java:66)
	at game.data.registries.RegistryLoader.lambda$forVersion$0(RegistryLoader.java:45)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at game.data.registries.RegistryLoader.forVersion(RegistryLoader.java:43)
	at config.Config.loadVersionRegistries(Config.java:262)
	at config.Config.lambda$getGameProtocol$0(Config.java:254)
	at java.lang.Thread.run(Unknown Source)

 Cannot run Minecraft version 1.17+ with a Java version below 16. You are currently using Java version 8.
Please consider upgrading your Java version to at least version 16.

game.UnsupportedMinecraftVersionException: Minecraft version 1.17 is not supported for java version 8
	at game.data.registries.RegistryLoader.getReportsFromServerJar(RegistryLoader.java:115)
	at game.data.registries.RegistryLoader.<init>(RegistryLoader.java:66)
	at game.data.registries.RegistryLoader.lambda$forVersion$0(RegistryLoader.java:45)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at game.data.registries.RegistryLoader.forVersion(RegistryLoader.java:43)
	at game.data.chunk.palette.GlobalPaletteProvider.requestPalette(GlobalPaletteProvider.java:46)
	at game.data.chunk.palette.GlobalPaletteProvider.getGlobalPalette(GlobalPaletteProvider.java:28)
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:98)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:234)
	at game.data.chunk.ChunkImageFactory.computeHeightMap(ChunkImageFactory.java:210)
	at game.data.chunk.ChunkImageFactory.<init>(ChunkImageFactory.java:40)
	at game.data.chunk.Chunk.getChunkImageFactory(Chunk.java:459)
	at gui.GuiMap.setChunkLoaded(GuiMap.java:446)
	at gui.GuiManager.setChunkLoaded(GuiManager.java:263)
	at game.data.WorldManager.lambda$loadChunk$0(WorldManager.java:270)
	at game.data.chunk.Chunk.afterParse(Chunk.java:295)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:71)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Chunk could not be parsed!

 Cannot run Minecraft version 1.17+ with a Java version below 16. You are currently using Java version 8.
Please consider upgrading your Java version to at least version 16.


 
	at game.data.chunk.palette.GlobalPaletteProvider.getGlobalPalette(GlobalPaletteProvider.java:28)
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:98)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:234)
	at game.data.chunk.ChunkImageFactory.computeHeightMap(ChunkImageFactory.java:210)
	at game.data.chunk.ChunkImageFactory.<init>(ChunkImageFactory.java:40)
	at game.data.chunk.Chunk.getChunkImageFactory(Chunk.java:459)
 
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

 Cannot run Minecraft version 1.17+ with a Java version below 16. You are currently using Java version 8.
Please consider upgrading your Java version to at least version 16.

game.UnsupportedMinecraftVersionException: Minecraft version 1.17 is not supported for java version 8
	at game.data.registries.RegistryLoader.getReportsFromServerJar(RegistryLoader.java:115)
	at game.data.registries.RegistryLoader.<init>(RegistryLoader.java:66)
	at game.data.registries.RegistryLoader.lambda$forVersion$0(RegistryLoader.java:45)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at game.data.registries.RegistryLoader.forVersion(RegistryLoader.java:43)
	at game.data.chunk.palette.GlobalPaletteProvider.requestPalette(GlobalPaletteProvider.java:46)
	at game.data.chunk.palette.GlobalPaletteProvider.getGlobalPalette(GlobalPaletteProvider.java:28)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:320)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:311)
	at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:108)
	at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:142)
	at game.data.chunk.Chunk.parseTileEntities(Chunk.java:285)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:70)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Chunk could not be parsed!


```

**Version**
 - Game: Minecraft 1.17.0
 - Downloader: latest
 - Launcher (if login issues): 2.2.3555 (last updated 7/12/2021)

**Comment by mircokroon** [comment]
Hmm strange, can you check your JAVA_HOME variable? it's possible that the .exe looks at that instead of the path

**Comment by brightcuttlefish** [comment]
JAVA_HOME was set incorrectly, changing it to C:\Program Files\Java\jdk-16.0.1\ solved this issue. Thanks!
