### ISSUE TITLE
New authentication does not work on MacOS

### ISSUE THREAD

**Issue by mygizli04** [mircokroon/minecraft-world-downloader#189]
**Describe the bug**
When I try to join the created server, the world downloader cannot get login details from the minecraft process (possibly because I'm on macOS)

**Steps to reproduce**
Simply try to join a world

**Log output**
```
Client probably disconnected. Waiting for new connection...
Something went wrong while trying to authenticate your Minecraft account.

Authentication details are retrieved from the Minecraft process's launch arguments. The game must be running for this to work.
Alternatively, use options --username and --token to specify the details manually.
See https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication for more details.

javax.security.sasl.AuthenticationException: Cannot get valid authentication details. [Caused by javax.security.sasl.AuthenticationException: Cannot find authentication details.]
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:40)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javax.security.sasl.AuthenticationException: Cannot find authentication details.
	at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:47)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:37)
	... 14 more
Client probably disconnected. Waiting for new connection..

```

**Version**
 - Game: Minecraft 1.17.1
 - Downloader: latest

**Comment by mircokroon** [comment]
Thanks, would you (or anyone else having issues on MacOS) mind running `ps -fC java` in a terminal while Minecraft is open, and posting the output here? Feel free to remove any identifying information (e.g. the auth token and username). 

Pretty sure the issue is with the output of it being different between Mac and Linux, but unfortunately I don't have access to any Mac device to test this with.

**Comment by mygizli04** [comment]
Hi, it appears linux's (at least ubuntu's) ps and macOS's ps take different arguments so the exact command you gave me did not work. Instead I found minecraft's pid and used that assuming that's what you were looking for. If it's wrong please let me know. I also redacted my username/token.

I used fabric as that's what I use normally but it doesn't work with vanilla either so I don't think that's the problem. Here's the output:
<details>
<summary> Output </summary>
```
  UID   PID  PPID   C STIME   TTY           TIME CMD
  502   799   782   0  2:01AM ??        23:58.39 /Users/[USERNAME]/Library/Application Support/minecraft/runtime/java-runtime-alpha/mac-os/java-runtime-alpha/jre.bundle/Contents/Home/bin/java -XstartOnFirstThread -Xss1M -Djava.library.path=/Users/[USERNAME]/Library/Application Support/minecraft/bin/77d5-a36b-2e41-3c59 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.2.3964 -cp /Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/fabricmc/tiny-remapper/0.4.2/tiny-remapper-0.4.2.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/fabricmc/intermediary/1.17.1/intermediary-1.17.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/fabricmc/fabric-loader/0.11.6/fabric-loader-0.11.6.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/github/oshi/oshi-core/5.7.5/oshi-core-5.7.5.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/Users/[USERNAME]/Library/Application Support/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar:/Users/[USERNAME]/Library/Application Support/minecraft/versions/fabric-loader-0.11.6-1.17.1/fabric-loader-0.11.6-1.17.1.jar -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dlog4j.configurationFile=/Users/[USERNAME]/Library/Application Support/minecraft/assets/log_configs/client-1.12.xml net.fabricmc.loader.launch.knot.KnotClient --username how_are_you --version fabric-loader-0.11.6-1.17.1 --gameDir /Users/[USERNAME]/Library/Application Support/minecraft --assetsDir /Users/[USERNAME]/Library/Application Support/minecraft/assets --assetIndex 1.17 --uuid 194cf04885734473837ec3c123875946 --accessToken [REDACTED] --userType mojang --versionType release
```
</details>

**Comment by mircokroon** [comment]
Hmm alright, well that explains the problem then I guess. 

What command did you use to get the full output? I had a look around and found `ps ax | grep "java"`, does that give a similar result? It'd be ideal if it's a single command that returns the correct data somewhere, the rest should be easy to sort out in code.

**Comment by mygizli04** [comment]
I used `ps -fC -p [PID]` as I already knew Minecraft's PID, `ps ax | grep "java"` also gives similar results but includes non-related things that have "java" in the path as well. I don't know how this world downloader detects the process, but maybe it could filter for the default minecraft path (which would be ~/Library/Application Support/minecraft) and give a command line option to change it from the default like before the new authentication. In my experience `ps ax | grep ~/Library/Application\ Support/minecraft/runtime` consistently gave the right output without me manually using the PID (excluding the grep process which should be easy to filter out).
