### ISSUE TITLE
Not working with 1.17 due to negative block height

### ISSUE THREAD

**Issue by evvanErb** [mircokroon/minecraft-world-downloader#191]
**Describe the bug**
Short description of what the bug is.

Error downloading chunk due to negative block height

**Steps to reproduce**
If possible, describe how the bug can be achieved.

Use with 1.17

**Log output**
```
java.lang.ArrayIndexOutOfBoundsException: Index -14 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)    
...

```
**Screenshots**

**Version**
 - Game: Minecraft 1.17
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
Ah, I guess I never tried this since it wont be enabled by default until 1.18. I'll see if I can do something about it.

**Comment by mircokroon** [comment]
Hmm I'm not able to reproduce this specific error, I did fix a few other issues with coordinates below 0 and above 256 so maybe one of those caused this

**Comment by Nullbczd** [comment]
> Ah, I guess I never tried this since it wont be enabled by default until 1.18. I'll see if I can do something about it.
Some 1.17.1 servers added 1.18 preview packets，Is there no solution for such a server？

**Comment by mircokroon** [comment]
Well, I set up a server with that and fixed that. Is this issue still occurring?

**Comment by Nullbczd** [comment]
> Well, I set up a server with negative block heights and fixed that. Is this issue still occurring?
Server IP address is server.mcbar.club
java.lang.ArrayIndexOutOfBoundsException: Index -139 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:126)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:118)
	at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:114)
	at game.data.chunk.Chunk.getNumericBlockStateAt(Chunk.java:307)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:315)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:311)
	at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:108)
	at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:142)
	at game.data.chunk.Chunk.parseTileEntities(Chunk.java:285)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:70)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!
