### ISSUE TITLE
Modded minecraft blocks vanishing

### ISSUE THREAD

**Issue by Matthew1239** [mircokroon/minecraft-world-downloader#204]
**Describe the bug**
Short description of what the bug is.
Modded blocks not appearing/ appearing as vanilla blocks
**Steps to reproduce**
If possible, describe how the bug can be achieved.
Have Java 8 and Java 16 installed, try to download modded chuncks. My modpack is 1.12.2 pack by xJon__ 
**Log output**
```
Exception in thread "Thread-7" java.lang.NullPointerException 
game.data.Class.method(Class.java:42)                              
game.data.OtherClass.method(OtherClass.java:48)           
...
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:358)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:332)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:426)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:403)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

 java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:358)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:332)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:426)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:403)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

 java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:358)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:332)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:426)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:403)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

```
**Screenshots**
![2021-08-28_14 39 57](https://user-images.githubusercontent.com/89692123/131218173-a63376f3-2841-4ea9-9d88-b6d245e800c6.png)
![2021-08-28_14 39 47](https://user-images.githubusercontent.com/89692123/131218175-94f6e451-8223-49cf-9324-e7b4e0f98448.png)

**Version**
 - Game: Minecraft 1.12.2
 - Downloader: latest
 - Launcher Technic Pack

**Comment by tort-oise** [comment]
https://github.com/mircokroon/minecraft-world-downloader/wiki/Features
