### ISSUE TITLE
Authentication fails from macOS using default Launcher w/Mojang account

### ISSUE THREAD

**Issue by k-willowhawk** [mircokroon/minecraft-world-downloader#205]
**Describe the bug**
I can't get the `world-downloader` proxy to authenticate, as it doesn't seem to be able to find my token, which is sorta suspect because it doesn't appear to be placed in the `launcher_accounts.json` file... Not sure if this is unique to macOS's version or whatnot.

**Steps to reproduce**

1. Install default Minecraft Launcher
2. Update to 1.17.1
3. Lanch a game and connect to a world.
4. (optional) Inspect `launcher_accounts.json` file.
5. Launch world-downloader with appropriate server/port params
6. Connect to localhost port

**Log output**
```
Something went wrong while trying to authenticate your Minecraft account.

Authentication details are retrieved from the Minecraft process's launch arguments. The game must be running for this to work.
Alternatively, use options --username and --token to specify the details manually.
See https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication for more details.

javax.security.sasl.AuthenticationException: Cannot get valid authentication details. [Caused by javax.security.sasl.AuthenticationException: Cannot find authentication details.]
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:40)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javax.security.sasl.AuthenticationException: Cannot find authentication details.
	at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:47)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:37)
	... 14 more
Client probably disconnected. Waiting for new connection...
Server probably disconnected. Waiting for new connection...
```
**Screenshots**

**Version**
 - Game: Minecraft 1.17.1
 - Downloader: latest
 - Launcher (if login issues): 2.2.3964
 - OS: macOS 11.5.2 (Big Sur)

**Comment by k-willowhawk** [comment]
I found another key/token in launcher_msa_credentials.bin but that doesn't work either (it complains that the key is only 164 characters, expected 308).

Is there some special place the token is stored on the macOS launcher?

**Comment by vrogojin** [comment]
Same on Windows. Auth token not anymore in launcher_accounts.json. Looks like this is an issue with account migration to Microsoft. I did not migrate to Microsoft account yet. Where can I find that token now?

**Comment by mircokroon** [comment]
Recently some changes to authentication made the old method (using `launcher_accounts.json`) impossible, so there's a new system now which looks at the running Minecraft process to find the token. On MacOS this is broken on the latest release, although it was fixed on the latest master branch version a week or two ago. I'll make a release to fix this at least for Mac today or tomorrow.

As for Windows, I'm not sure what could be wrong there. It looks for processes of `javaw.exe` that are running, can you confirm that when Minecraft is active there is at least one such process visible in task manager -> Details? Maybe there are other possible names for the process on some systems that I should account for.

**Comment by mircokroon** [comment]
Should be fixed on the latest release, I'll close this since the main issue is resolved.
