### ISSUE TITLE
Modded blocks are not saved 1.16.6 ATM6

### ISSUE THREAD

**Issue by rs3guy** [mircokroon/minecraft-world-downloader#208]
**Describe the bug**
I am currently in a ATM6 modded server. When I try to use this program it works, but it automatically says there was an error.
When I go to load the saved world, ALL the modded blocks are gone, but the vanilla blocks are all there.

**Log output**
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:358)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:332)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:426)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:403)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:358)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:332)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:426)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:403)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

 java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null

 java.lang.NullPointerException


)           
...

```

**Version**
 - Game: Minecraft 1.16.5
 - Downloader: latest

**Comment by rs3guy** [comment]
Was I mistaken that this program is supposed to be usable with mods? And does it not work with 1.16.5? Can I get anyone to help me please?

**Comment by mircokroon** [comment]
It it supposed to, this seems to be a bug. I'll look into the issue hopefully soon. That said, it is currently not able to correctly download most modded blocks, so they may be missing.
