### ISSUE TITLE
InputMismatchException: Number of provided blocklight maps does not match provided mask

### ISSUE THREAD

**Issue by edelsone** [mircokroon/minecraft-world-downloader#212]
**Describe the bug**
Getting an error message about blocklight maps not matching mask

**Steps to reproduce**
1: Connect to server through the downloader.
2: Walk around.

**Log output**
```
java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6, 11, 12, 13} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {2, 4, 5, 6, 11, 12, 13, 14} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6, 11, 12, 13} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)

 java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 4, 5} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6, 8} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6, 7, 8} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.util.InputMismatchException: Number of provided blocklight maps does not match provided mask: {1, 2, 3, 4, 5, 6} != 2048
	at game.data.chunk.version.Chunk_1_17.updateLight(Chunk_1_17.java:159)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:136)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
```
**Screenshots**
N/A

**Version**
 - Game: Minecraft 1.17.1
 - Downloader: Release 1.14.5
 - Launcher (if login issues): 2.2.3965

**Comment by mircokroon** [comment]
Thanks! Should be fixed now.
