### ISSUE TITLE
How am I supposed to use it?

### ISSUE THREAD

**Issue by Pacal08** [mircokroon/minecraft-world-downloader#226]
I got this error, double checked everything. when trying to use the jar file I get the following error:

>java -jar "C:\Users\#####\Desktop\world-downloader.jar" -s ###.###.###.233:25565 -m ~/.minecraft
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

![epicfail](https://user-images.githubusercontent.com/92452656/137159347-c7b1885a-b60c-4503-b491-161db08f64c0.png)

**Comment by Pacal08** [comment]
thanks, now i tried again in the GUI, it working. Thanks again, really great program!
