### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by iOussama** [mircokroon/minecraft-world-downloader#238]
**Problem: I did put on auth token and my username and i got this**

**Error:**
*java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:56)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.IllegalStateException: Packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
	at packets.DataReader.readPackets(DataReader.java:172)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:831)*

**Comment by mircokroon** [comment]
probably the auth token was incorrect somehow, not sure what might have caused this otherwise
