### ISSUE TITLE
MultiMC with Microsoft account?

### ISSUE THREAD

**Issue by LinuxSushi** [mircokroon/minecraft-world-downloader#239]
**Describe the bug**
When using MultiMC with Meteor + BleachHack on my Microsoft account on Windows 10 Home Edition, I am unable to use World Downloader (it disconnects me when I try.) I tried following the instructions at https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication, however, `wmic process where "name like 'java%'"` does not show my access token. Manually setting the access token does not work either. I tried copying and pasting every entry named `token` in MultiMC's `accounts.json` many times over to no avail.

**Log output**
```
 Something went wrong while trying to authenticate your Minecraft account.

Authentication details are retrieved from the Minecraft game directly. Make sure that the game is running.
If you have a username set in the authentication tab, ensure that it matches the one you are trying to connect with.
If you are in an environment where this does not work, please set the correct username and token in the authentication tab.
See https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication for more details.

javax.security.sasl.AuthenticationException: Cannot get valid authentication details. [Caused by javax.security.sasl.AuthenticationException: Cannot find authentication details.]
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:40)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javax.security.sasl.AuthenticationException: Cannot find authentication details.
	at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:47)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:37)
	... 14 more
```

**Version**
 - Game: Minecraft 1.17.1
 - Downloader: latest
 - Launcher (if login issues): 0.6.13

**Comment by mircokroon** [comment]
It seems MultiMC works different nowadays so unfortunately it's not possible to use with MultiMC currently. I'll see if this can be fixed soon.

**Comment by GodSaveTheDoge** [comment]
You should find the token in ~/.local/share/multimc/accounts.json I guess

**Comment by MisterNoNameLP** [comment]
A workaround is to use the token generated by the official launcher, but then connect using a MultiMC instance.

**Comment by imnusyandlazy** [comment]
fix for easyMc too?

**Comment by imnusyandlazy** [comment]
i did try and find the alt token and i did then put in the right details and when i tried useing it with easyMC it just said "disconnected"

**Comment by lynrayy** [comment]
Reopen, EasyMC still not working in meteor
