### ISSUE TITLE
1.18.1 chunk exception (rareish)

### ISSUE THREAD

**Issue by cdnmodule** [mircokroon/minecraft-world-downloader#280]
**Log output**
```
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
        at packets.DataReader.readVarInt(DataReader.java:70)
        at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
        at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:71)
        at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:46)
        at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:104)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:121)
        at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:81)
        at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
...

```

**Comment by nickmcaa** [comment]
Im getting this error too, any fixes?
