### ISSUE TITLE
1.18.1 Index out of bounds

### ISSUE THREAD

**Issue by murmelgrumpf** [mircokroon/minecraft-world-downloader#286]
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 53970 out of bounds for length 53970
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider$1.read(DataTypeProvider.java:191)
	at java.base/java.io.InputStream.read(InputStream.java:293)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at se.llbit.nbt.StringTag.read(StringTag.java:46)
	at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
	at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:188)
	at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:68)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:62)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 36135 out of bounds for length 36135
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider$1.read(DataTypeProvider.java:191)
	at java.base/java.io.InputStream.read(InputStream.java:293)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at se.llbit.nbt.StringTag.read(StringTag.java:46)
	at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
	at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:188)
	at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:68)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:62)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!

 java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at packets.DataTypeProvider.readVarIntArray(DataTypeProvider.java:181)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:65)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 	at packets.DataReader.readVarInt(DataReader.java:70)

 java.lang.ArrayIndexOutOfBoundsException

 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!

 	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)

 java.lang.ArrayIndexOutOfBoundsException

 	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)

 java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.

 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 20 out of bounds for byte[17]

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!

```

**Comment by nickmcaa** [comment]
Im Getting these same errors, anyone have a fix?

**Comment by JackyHe398** [comment]
same for me

**Comment by woodendoors7** [comment]
same
