### ISSUE TITLE
I have the latest java

### ISSUE THREAD

**Issue by szalony9szymek** [mircokroon/minecraft-world-downloader#29]
java -jar world-downloader.jar -s hypixel.net
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

Please help

**Comment by szalony9szymek** [comment]
The java version inside of the launcher is "1.8.0_51"
The one installed on my pc is "1.8.0_251"
(I am talking about JRE, tho I also have the latest version of JDK)

**Comment by mircokroon** [comment]
As stated in the readme, Java 1.9 is required. Java 1.8 is not the latest version, in fact we're up to version 14 now.

**Comment by szalony9szymek** [comment]
I can start it now. Thanks

**Comment by Cookietank** [comment]
hi, I'm really sorry I have the same issue. what was it that fixed this??

**Comment by szalony9szymek** [comment]
as mircokroon said, just install java 9 or newer, I used java 10 - jre-10.0.2_windows-x64_bin.exe and jdk-10.0.2_windows-x64_bin.exe from [here](https://www.oracle.com/java/technologies/java-archive-javase10-downloads.html) (you need an account, it is free)

**Comment by szalony9szymek** [comment]
If you give me your google drive email i can share this files with you there
