### ISSUE TITLE
App doesn't support negative Y coordinates on 1.17.1

### ISSUE THREAD

**Issue by amirave** [mircokroon/minecraft-world-downloader#290]
**Describe the bug**
It seems that the downloader does not support taller worlds on 1.17.1, which don't occur naturally but are actually possible using datapacks.

**Steps to reproduce**
This bug can be reproduced using datapacks that change the maximum height or minimum Y of a world. I'm specifically using the Terralith world generation datapack, with a vanilla client.

**Log output**
```
java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!
```
and also:
```
java.lang.ArrayIndexOutOfBoundsException: Index -79 out of bounds for length 256
        at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
        at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:126)
        at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:118)
        at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:114)
        at game.data.chunk.Chunk.getNumericBlockStateAt(Chunk.java:307)
        at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:315)
        at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:311)
        at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:108)
        at game.data.chunk.ChunkEntities.addTileEntity(ChunkEntities.java:142)
        at game.data.chunk.Chunk.parseTileEntities(Chunk.java:285)
        at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:70)
        at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
        at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
        at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
        at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
```

**Version**
 - Game: Minecraft 1.17.1
 - Downloader: latest

**Comment by rautamiekka** [comment]
> **Version**
> * Downloader: latest

Invalid version.

**Comment by mircokroon** [comment]
Duplicate of #191
