### ISSUE TITLE
Error trying to download a world

### ISSUE THREAD

**Issue by Thijs747** [mircokroon/minecraft-world-downloader#297]
**Describe the bug**
When trying to download a world, I enter the server IP, I get promted to join localhost:25565. After doing so, I get an error. Report attached below.

**Ingame error**
```
Internal Exception: io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException: readerIndex(23986) + length(1) exceeds writerIndex(23986): UnpooledHeapBytebuf(ridx: 23986, widx: 23986, cap: 23986/23986)
```

**Log output**
```
java.lang.ArrayIndexOutOfBoundsException: Index 34508 out of bounds for length 34508
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider$1.read(DataTypeProvider.java:191)
	at java.base/java.io.InputStream.read(InputStream.java:293)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at se.llbit.nbt.StringTag.read(StringTag.java:46)
	at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
	at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:188)
	at game.data.chunk.version.Chunk_1_14.parseHeightMaps(Chunk_1_14.java:68)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:62)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 20 out of bounds for byte[17]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readLongArray(DataTypeProvider.java:165)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:148)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.

 	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
```

**Version**
 - Game: Minecraft (Newest release unmodified) 1.18.1
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
Are you using the pre-release?

**Comment by Thijs747** [comment]
This is with the latest full release (downloaded from the releases tab). The server is on 1.18.1. No pre-releases.

**Comment by JackyHe398** [comment]
@mircokroon i have the same problem for downloading

here is my computers' information
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
OS: win 10 pro for pc1
win 11 dev for pc2
server version: 1.18.1 snapshot and latest

i have test for serveral combination in 1.18.1, all fail
1. client, server and the downloader in same pc in 1.18.1 version
2. client in pc2, server and the downloader in pc 1 in 1.18.1 version
3. client and downloader in pc2 and server in pc 1 in 1.18.1 version
4. client and downloader in pc1, using hypixel server 1.18.1 version
5. downloader in pc1 and downloader in pc2, using hypixel server 1.18.1 version

Simpily, those tests can conclude that, the OS version among windows will not affect the problem. The different server version(within 1.18.1) will not affect the result. Also, i tried to update, downgrade all the java and server version(still in 1.18.1) to stable version or older version, the problem still exist

Further, i am trying to downgrade the server and client to 1.17, all working perfectly. so i conclude that the downloader now is not able to download 1.18.1 files.
