### ISSUE TITLE
1.18 prerelease big issues.

### ISSUE THREAD

**Issue by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [mircokroon/minecraft-world-downloader#339]
**Describe the bug**
chests, signs, beds are invisible on a wdl, everything inside the chest is not saved despite I did open each, entity owner names and stuff like that isn't saved as well, it sometimes also doesn't save exact chunk you're logging in to when connecting to localhost. 

**Steps to reproduce**
just run and try to download world on 1.18.2 then bring the save to saves in .minecraft

**Log output**
it did throw some error thing but it can be also easily reproduced as I said before. if needed I can still do it again and send the log 
**Version**
 - Game: Minecraft 1.18.2
 - Downloader: latest

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
```
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:73)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:44)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:121)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:81)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!

 java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:73)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:44)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:121)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:81)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!
```
here's the log

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
also the same thing occurs when I'm downloading the world on 1.18.1 too. same errors, no chunk and no chests and stuff
