### ISSUE TITLE
getting a java.lang.RuntimeException: Client not authenticated! error

### ISSUE THREAD

**Issue by GrandSheikMIke** [mircokroon/minecraft-world-downloader#344]
when i use manual authentication, and attempt to connect to the localhost, a client auth error occurs

**Log output**
```java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:56)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

Exception in thread "Thread-7" java.lang.NullPointerException 
game.data.Class.method(Class.java:42)                              
game.data.OtherClass.method(OtherClass.java:48)           
...



**Version**
 - Game: Minecraft 1.18.1
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by xXPerditorXx** [comment]
I have the same problem... I think it is because Mojang Auth isn't used anymore. Now it is Microsoft and this couldn't be included. But I'm not sure.
