### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Crystaxu** [mircokroon/minecraft-world-downloader#345]
when i try to join to the local host i get this error. 

**log**
i think this is the log
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider.readShort(DataTypeProvider.java:121)
	at game.data.chunk.version.Chunk_1_14.readBlockCount(Chunk_1_14.java:48)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:130)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 20 out of bounds for byte[17]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readLongArray(DataTypeProvider.java:165)
	at game.data.chunk.Chunk.readChunkColumn(Chunk.java:148)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:68)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.chunk.version.Chunk_1_17.parse(Chunk_1_17.java:64)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:108)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:125)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:85)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException
Chunk could not be parsed!
![2022-05-02 13_08_41-Minecraft 1 18 2](https://user-images.githubusercontent.com/43451345/166218747-214a61be-0509-4331-a3e2-8eb463a1fc86.png)

**Version**
 - Game: Minecraft 1.18.2
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by AgileGhost** [comment]
From the looks of it, it seems that the world downloader is detecting blocks outside of the normal range for 1.17 eg. above 256 and below 0. This error is fixed with the last few commits however it isn't released so it will need to be compiled from the source. The latest version isn't able to save chests, signs and a few others and will spit an error when there is a bed too.
