### ISSUE TITLE
Can't connect to server but can connect via minecraft

### ISSUE THREAD

**Issue by zirus23** [mircokroon/minecraft-world-downloader#35]
Running it in ubuntu 18 on windows (WSL) gives me the following error. The server is not down or on  a different address since I can join it via this IP from minecraft. The world in the server is vanilla 1.16.2

`➜  Downloads java -jar world-downloader.jar -s 192.99.16.106
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.     
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
        at gui.GuiManager.createAndShowGUI(GuiManager.java:34)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)       
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Starting proxy for 192.99.16.106. Make sure to connect to localhost:25565 instead of the regular server address.
Cannot connect to 192.99.16.106. The server may be down or on a different address.`

**Comment by ChillerDragon** [comment]
``No X11 DISPLAY variable was set`` I doubt this is causing the issue but when you want to use the gui you have to do that.
Try ``export DISPLAY=:0`` for example. You can also try not running it from WSL and run in native windows. WSL is famous for making trouble.

**Comment by zirus23** [comment]
Yeah I tried doing it in powershell but my java was broken in powershell so I gave up. Do you know how I could run a .ps1 script in powershell (to install java)? It's some permission issue. If not you can close this issue since it's not relevant, I'm sure the solution is probably running it in powershell.

`C:\Users\swarn\Downloads\scipt.ps1 : File C:\Users\swarn\Downloads\scipt.ps1 cannot be loaded because running scripts
is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ C:\Users\swarn\Downloads\scipt.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess`

**Comment by mircokroon** [comment]
Another solution for that is to disable the UI with `--gui=false`. 

The GUI issue is likely not related to being unable to connect though. Perhaps the server is running on a particular port that you're not including? I assume the server is supposed to be public, and I can't see the server from Minecraft either.

**Comment by zirus23** [comment]
I'll try it with no gui. As for the server it's nianticinterns.serv.lol, I tried both with that as well as with converting it to ip.

**Comment by mircokroon** [comment]
Looks like it's on port `25587`, so adding `-p 25587` should fix it.

**Comment by zirus23** [comment]
Adding port seems to resolve the connection issue, but I get another error. I looked it up and can't find anything pointing to the .minecraft directory.

`Cannot read or find '~/.minecraft/launcher_profiles.json'!
Use launch option: "-m /path/to/.minecraft/" to indicate the location of your Minecraft installation`

**Comment by mircokroon** [comment]
Do you know where your Minecraft installation is located? You need to include the path as shown there so that it can read the `launcher_profiles.json` file and authenticate you. 

An easy way to find your Minecraft directory is to go to `Options` > `Resource Packs..` > `Open Pack Folder` in-game. Make sure to go one folder up from there to get your Minecraft directory.

**Comment by ChillerDragon** [comment]
> Adding port seems to resolve the connection issue, but I get another error. I looked it up and can't find anything pointing to the .minecraft directory.
> 
> `Cannot read or find '~/.minecraft/launcher_profiles.json'! Use launch option: "-m /path/to/.minecraft/" to indicate the location of your Minecraft installation`

Since it thinks you use a linux system with minecraft installed in linux it expectes your mc directory to be at ``~/.minecraft`` so use -m to provide the correct path to your minecraft directory which is probably on your windows system. So go to windows and navigate in the explorer to %APPDATA%\minecraft and shift+rightclick -> open linux shell here then type ``pwd`` and use that value to pass to mc downloader using the ``-m`` option

**Comment by zirus23** [comment]
Finally worked, thanks!
For anyone else who finds this issue, this is the command I had to run on ubuntu on windows for it to work

`java -jar world-downloader.jar -s your.server.name.here -p 25587 -m /mnt/c/Users/swarn/AppData/Roaming/.minecraft`
