### ISSUE TITLE
make it work with client's

### ISSUE THREAD

**Issue by imnusyandlazy** [mircokroon/minecraft-world-downloader#360]
make it work with clients such as lunar, badlion and easyMC

**Comment by mircokroon** [comment]
Have you verified it does not work on any of these? Most clients should work normally, at least one of these has worked fine in the past as well.

**Comment by imnusyandlazy** [comment]
yes i tried with lunar and badlion and easyMC but non of them worked

**Comment by imnusyandlazy** [comment]
> Have you verified it does not work on any of these? Most clients should work normally, at least one of these has worked fine in the past as well.

it just said "not autherticed client" or whatever

**Comment by imnusyandlazy** [comment]
is it possible tho to make it work with easyMC alt's?

**Comment by imnusyandlazy** [comment]
is it cus i use fabric?

**Comment by imnusyandlazy** [comment]
![World Downloader - Settings 6_4_2022 6_30_08 PM](https://user-images.githubusercontent.com/106879376/172016366-bef0b2b6-04bd-4886-9948-91d6a9597cfb.png)

**Comment by imnusyandlazy** [comment]
Something went wrong while trying to authenticate your Minecraft account.

Authentication details are retrieved from the Minecraft game directly. Make sure that the game is running.
If you have a username set in the authentication tab, ensure that it matches the one you are trying to connect with.
If you are in an environment where this does not work, please set the correct username and token in the authentication tab.
See https://github.com/mircokroon/minecraft-world-downloader/wiki/Authentication for more details.

javax.security.sasl.AuthenticationException: Cannot get valid authentication details. [Caused by javax.security.sasl.AuthenticationException: Cannot find authentication details.]
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:40)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.security.sasl.AuthenticationException: Cannot find authentication details.
	at proxy.auth.AuthDetailsManager.getAuthDetails(AuthDetailsManager.java:47)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:37)
	... 14 more
java.lang.IllegalStateException: Packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
	at packets.DataReader.readPackets(DataReader.java:172)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:56)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:113)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mircokroon** [comment]
I was able to get it to work on Badlion just now without any issues. In any case this will be resolved along with #239 soon™ so I'll close this as a duplicate.

**Comment by imnusyandlazy** [comment]
oh
