### ISSUE TITLE
1.19 realms not working

### ISSUE THREAD

**Issue by LordVertice** [mircokroon/minecraft-world-downloader#376]
**Describe the bug**
It seems that it's impossible to join a realm on 1.19, error message in screenshot section. The WDL can be started, but once you try to connect to the local server it will immediately crash.

**Steps to reproduce**
Simply try connecting to any 1.19 realm, then join the local server.

**Log output**
(no error in latest.log, this is the only bit that shows up after startup, the logs end after this)
```
[20:53:19] [Render thread/INFO]: Connecting to localhost, 25565
```
To me this looks like there is no error in MC, just the client being unable to connect to the local server since it crashes immediately

**Screenshots**
![image](https://user-images.githubusercontent.com/56739341/172461013-b31cbefa-f450-4a07-b750-af45ab4f8da2.png)

**Version**
 - Game: Minecraft 1.19
 - Downloader: latest

**Comment by Tsoccerguy3** [comment]
I know Microsoft blocks localhost on Bedrock realms but this can be changed in registry. I wonder if they do this on Java as well

**Comment by mircokroon** [comment]
1.19 is not supported yet so probably its that

**Comment by LordVertice** [comment]
> 1.19 is not supported yet so probably its that

I figured as much, but it seemed that nobody tried it before me (realms usually take days before they upgrade, but there are tricks), and I thought you might want to know what kinds of errors show up. And who knows, maybe it could've magically worked on its own ¯\_(ツ)_/¯

**Comment by mircokroon** [comment]
Sadly it rarely is that easy :(

**Comment by AgileGhost** [comment]
Here is the error that seems to cause a crash on 1.19
```js
javax.crypto.BadPaddingException: Decryption error
        at java.base/sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:369)
        at java.base/sun.security.rsa.RSAPadding.unpad(RSAPadding.java:282)
        at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:366)
        at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:400)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2206)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:205)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:100)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:30)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
Encryption failure! Terminating.
```

**Comment by LordVertice** [comment]
Perhaps Mojang updated MCs encryption protocols? That'd explain why WDL breaks, since it specifically relies on tunneling your connection to the server through itself

**Comment by LordVertice** [comment]
The crash still occurs in 1.19, and it seems like it happens on normal servers as well, see #389 (possible duplicate of this issue)
