### ISSUE TITLE
Doesn't work in 1.18.2 (Bungeecord)

### ISSUE THREAD

**Issue by Troughy** [mircokroon/minecraft-world-downloader#385]
**Describe the bug**
I've only really tried this on one server, which has more worlds (Bungeecord, but I haven't seen anything that says it doesn't work with Bungee). When I join I instantly get an error and also black chunks. I've been trying different settings but there is no documentation so I don't know what I'm doing. I joined the survival server, spent 10 minutes walking around, saved, then when I checked the map there were worlds with names I didn't recognize, also it literally saved only 1 chunk of the survival world. I also don't understand the Offset option, does 0 mean that the downloaded map will be at the same coordinates as it was on the server?

**Log output**
```
java.lang.ArrayIndexOutOfBoundsException: Index 303 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:125)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:117)
	at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:113)
	at game.data.chunk.Chunk.getNumericBlockStateAt(Chunk.java:311)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:319)
	at game.data.chunk.ChunkImageFactory.createImage(ChunkImageFactory.java:128)
	at gui.GuiMap.setChunkLoaded(GuiMap.java:459)
	at gui.GuiManager.setChunkLoaded(GuiManager.java:283)
	at game.data.WorldManager.lambda$loadChunk$0(WorldManager.java:284)
	at game.data.chunk.Chunk.afterParse(Chunk.java:299)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:63)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:121)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:81)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.ArrayIndexOutOfBoundsException: Index 303 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:125)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:117)
	at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:113)
	at game.data.chunk.Chunk.getNumericBlockStateAt(Chunk.java:311)
	at game.data.chunk.Chunk.getBlockStateAt(Chunk.java:319)
	at game.data.chunk.ChunkImageFactory.createImage(ChunkImageFactory.java:128)
	at game.data.WorldManager.chunkLoadedCallback(WorldManager.java:297)
	at game.data.chunk.ChunkImageFactory.<init>(ChunkImageFactory.java:41)
	at game.data.chunk.Chunk.getChunkImageFactory(Chunk.java:463)
	at gui.GuiMap.setChunkLoaded(GuiMap.java:452)
	at gui.GuiManager.setChunkLoaded(GuiManager.java:283)
	at game.data.WorldManager.lambda$loadChunk$0(WorldManager.java:284)
	at game.data.chunk.Chunk.afterParse(Chunk.java:299)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:63)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:121)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:81)
	at game.data.chunk.ChunkFactory.lambda$addChunk$1(ChunkFactory.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

...

```
**Screenshots**
![kép](https://user-images.githubusercontent.com/76389815/173187251-ea43c524-5bec-47e2-99d8-ca386dfed371.png)

**Version**
 - Game: Minecraft 1.18.2
 - Downloader: latest
 - Launcher (if login issues): latest

**Comment by mircokroon** [comment]
None of the settings have any relevance to parsing & savings chunks normally. This is likely some bug only present on some specific server configurations, can't really do anything about it without being able to reproduce the problem.

**Comment by Troughy** [comment]
> None of the settings have any relevance to parsing & savings chunks normally. This is likely some bug only present on some specific server configurations, can't really do anything about it without being able to reproduce the problem.

If you have some spare time you can perhaps join it yourself. The IP is play.pro-phoenix.net. You will probably get kicked first time, just reconnect.

**Comment by Tsoccerguy3** [comment]
I tried to connect to that server in 1.18.2 vanilla client , That server is blocking connections for what ever reason . It does not look like a down-loader issue . Have you tried and succeeded with a vanilla client connection .

**Comment by Troughy** [comment]
Looks like you can only connect from Hungary, not my server so can't do anything about that 😕

**Comment by mircokroon** [comment]
that makes it pretty hard to debug unfortunately

**Comment by Troughy** [comment]
It's not only that server though. I'm using 1.18.2 and maybe there are some differences in the code (since 1.16), you should check the BlockLocationEncoder. Also if possible it would be nice if it didn't download everything in one world, as when I'm downloading multiple worlds it overwrites them.
