### ISSUE TITLE
Cipher issue

### ISSUE THREAD

**Issue by FamousL** [mircokroon/minecraft-world-downloader#392]
Looks like I am having encryption issues, Am I just missing a package somewhere?

java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/CFB8/NoPadding
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:571)
	at proxy.EncryptionManager.lambda$enableEncryption$15(EncryptionManager.java:364)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
	at proxy.EncryptionManager.enableEncryption(EncryptionManager.java:361)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$13(EncryptionManager.java:331)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:312)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:220)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:209)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:50)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.security.NoSuchAlgorithmException: Unsupported mode CFB8
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Cipher.engineSetMode(P11Cipher.java:223)
	at java.base/javax.crypto.Cipher$Transform.setModePadding(Cipher.java:385)
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:564)
	... 17 more
Encryption failure! Terminating.

**Comment by mircokroon** [comment]
I guess you have some Java installation that doesn't support this, might be fixable by installing a different Java distribution but I'm not sure

**Comment by FamousL** [comment]
Found the problem, it appears that this encryption isn't fips compliant so it was disabled on my system, disabling fips mode allowed it to work.
