### ISSUE TITLE
Multiple errors, 1.18.2

### ISSUE THREAD

**Issue by JustASpeedrunner** [mircokroon/minecraft-world-downloader#395]
**Describe the bug**
Getting the below log output when walking around, and upon opening chests I get another, below the shorter one. I also get red chunks in the gui.

**Steps to reproduce**
Start program, authenticate through microsoft login, input "play.plagueblvd.com" in server ip, join localhost server

**Log output**
```
Generating reports for version 1.18.
Can't (fully?) parse chunk at (432, -255, minecraft:overworld). Cause: For input string: "18-ea"
```
```
java.lang.NullPointerException: Cannot invoke "game.data.container.MenuRegistry.getSlotCount(int)" because the return value of "game.data.registries.RegistryManager.getMenuRegistry()" is null
	at game.data.container.InventoryWindow.<init>(InventoryWindow.java:39)
	at game.data.container.ContainerManager.openWindow(ContainerManager.java:58)
	at packets.handler.version.ClientBoundGamePacketHandler_1_14.lambda$new$1(ClientBoundGamePacketHandler_1_14.java:52)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
```
**Screenshots**
![image](https://user-images.githubusercontent.com/30637257/174418105-6adf4b08-9054-4073-aab0-c1c01f6bdcc7.png)

**Version**
 - Game: Minecraft 1.18.2
 - Downloader: latest
 - Launcher: PolyMC, latest

**Comment by mircokroon** [comment]
Does it cause any issues with downloading the world? If not its probably fine to just ignore them, could be the server doing something unusual

**Comment by JustASpeedrunner** [comment]
Downloading is completely broken, when I take what it downloaded and open the world it is nothing but void and random structures.

**Comment by SteelingEye** [comment]
Did u ever get the world to download?

**Comment by JustASpeedrunner** [comment]
Nope, haven't really played minecraft in the past year, let alone use this program, so I'm unsure if this is even still an issue. If you're having the same issue I hope you can get it resolved.

**Comment by SteelingEye** [comment]
Moreso wanted the world download from the plague server xd
