### ISSUE TITLE
Crashing after a while

### ISSUE THREAD

**Issue by adabugra** [mircokroon/minecraft-world-downloader#402]
**Describe the bug**
I am trying to download 1.12.2 world and when i am starting to download after a while program freezes and crashes

**Log output**
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4706)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException

 java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException

 java.lang.NullPointerException
java.lang.NullPointerException


```

**Version**
 - Game: Minecraft 1.12.2
 - Downloader: latest
 - Launcher (if login issues): 1.12.2

**Comment by adabugra** [comment]
![image](https://user-images.githubusercontent.com/57899270/175511528-043e562c-1950-4ecf-8306-a70f53e4425f.png)

**Comment by luigi052005** [comment]
I have the same problem

**Comment by adabugra** [comment]
> I have the same problem

Use the jar version instead of exe. It fixed my problem
