### ISSUE TITLE
ERROR JAVA

### ISSUE THREAD

**Issue by Earo16S** [mircokroon/minecraft-world-downloader#409]
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MrAn0nym** [comment]
Link to currently fixed version https://github.com/SesuMoe/minecraft-world-downloader/releases/tag/1.19.1
