### ISSUE TITLE
Can't Run Executable nor Jar

### ISSUE THREAD

**Issue by Scruq445** [mircokroon/minecraft-world-downloader#413]
**Describe the bug**
The Executable only shows "This Application Requires Java Runtime 17" Even though I already have the latest java runtime.
**Steps to reproduce**
Run the Program or Jar

**Log output**
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Version**
 - Game: Minecraft 1.19 Fabric
 - Downloader: latest

**Comment by rautamiekka** [comment]
> The Executable only shows "This Application Requires Java Runtime 17" Even though I already have the latest java runtime.

Run these commands:
```
java -version

where java
```

>  - Downloader: latest

"latest" ain't a valid version number.

**Comment by IeuanK** [comment]
Make sure you are using JDK/JRE 17, not 18: https://www.oracle.com/java/technologies/downloads/#jdk17-windows
