### ISSUE TITLE
Abstract Method Error when trying to run through commandline on Mac

### ISSUE THREAD

**Issue by AWinterscheidt** [mircokroon/minecraft-world-downloader#421]
Receiving the following error when trying to run on Mac. Error repeats infinitely until process is terminated.
`java.lang.AbstractMethodError: Receiver class com.sun.glass.ui.mac.MacTimer does not define or inherit an implementation of the resolved method 'abstract void _pause(long)' of abstract class com.sun.glass.ui.Timer.
	at com.sun.glass.ui.Timer.pause(Timer.java:143)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pauseTimer(QuantumToolkit.java:514)
	at com.sun.javafx.tk.quantum.QuantumToolkit.postPulse(QuantumToolkit.java:501)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$12(QuantumToolkit.java:355)`

**Comment by smatian** [comment]
Did you fix this?

**Comment by kmbrady42** [comment]
I'm having this issue as well. M1 Ultra Mac Studio
