### ISSUE TITLE
Does not save chunks, spams ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by F3NXCorgi** [mircokroon/minecraft-world-downloader#425]
Immediately gets an error upon logging in, mostly ArrayIndexOutOfBounds exceptions.

Log output
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[3]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.version.DataTypeProvider_1_14.readCoordinates(DataTypeProvider_1_14.java:13)
	at game.data.commandblock.CommandBlockManager.readAndStoreCommandBlock(CommandBlockManager.java:27)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$6(ServerBoundGamePacketHandler.java:73)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

These repeat infinitely while the program is open.

 - Game: Minecraft 1.19.1
 - Downloader: latest

**Comment by yupyuptrp** [comment]
i have the same thing too

**Comment by instalab** [comment]
I can confirm, it's happening in 1.19.2

**Comment by RedCommander735** [comment]
Can also confirm, 1.19.2 on a paper server.

**Comment by MrAn0nym** [comment]
What java version are you using (openjdk, oracle etc.)?

**Comment by MrAn0nym** [comment]
Link to currently fixed version https://github.com/SesuMoe/minecraft-world-downloader/releases/tag/1.19.1

**Comment by alexvermaning0** [comment]
im also having a lot of out of bounds exception while trying to download part of an theme park server
https://pastebin.com/VQxg62Bd

**Comment by MrAn0nym** [comment]
> im also having a lot of out of bounds exception while trying to download part of an theme park server
> 
> https://pastebin.com/VQxg62Bd

Have you tried the newest release?

**Comment by alexvermaning0** [comment]
the one from 16 days ago yes.

**Comment by Troughy** [comment]
Same error.. It's been half a year
