### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by vasyaaliseychik** [mircokroon/minecraft-world-downloader#43]
I'm using an 1.5.4 release and 1.16.1 minecraft. running on windows 10 x64.
different servers show different error messages.
I can connect to the one of these servers, but world is blank
and this `Using protocol of game version 1.16.0 (736)` appears in console
on another servers there isn't any error messages. Just can't connect.
please help.

**Comment by ChillerDragon** [comment]
@vasyaaliseychik thats not a lot to work with. Could you maybe provide full log output? Or which servers did you try?

**Comment by vasyaaliseychik** [comment]
I tried mc.imptovskii.ru
`Reading profile information from C:\Users\Вася\AppData\Roaming\.minecraft\launcher_profiles.json`
`Starting proxy for mc.imptovskii.ru. Make sure to connect to localhost:25565 instead of the regular server address.`
`Performed handshake with mc.imptovskii.ru:25565, protocol version 736 :: next state: login`
`Login by: koneshno_vasya1`
`Enabled compression`
`Login success: koneshno_vasya1 logged in with uuid e83b5c76b0a3d9284a84e2310507591`
`Using protocol of game version 1.16.0 (736)`
then i connect to localhost and see the blank world and then time out happens

**Comment by mircokroon** [comment]
I'm able to connect to this server without any issues.
- What command are you using to start the application?
- Is there anything in the console after the timeout?

**Comment by vasyaaliseychik** [comment]
java -jar world-downloader.jar -s mc.imptovskii.ru
no

**Comment by mircokroon** [comment]
Does it work on other servers?

**Comment by littledrew22** [comment]
ive got the same issue but it gives an error so fast i cant read it and no output

**Comment by SovietSloth** [comment]
I get this problem but I am on 20w27a so I am not sure if it doesnt work on that version

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by mircokroon** [comment]
@SovietSloth that's not related to this, you just need to update Java

**Comment by SovietSloth** [comment]
I did

**Comment by Tragafantas** [comment]
Maybe its your internet connection
