### ISSUE TITLE
Don't working -> Client not authenticated! 403: Forbidden

### ISSUE THREAD

**Issue by PanetiX** [mircokroon/minecraft-world-downloader#431]
**Describe the bug**
Don't working, i just get a error.

**Steps to reproduce**
Download the latest world-downloader.jar
start cmd
change to folder which contains world-downloader.jar
enter command "java -jar world-downloader.jar -s censored.com" (i entered correct server adress)
open minecraft and connect to "localhost".
every server i tried says lost connection and i get a error on console log

**Log output**
```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @7a07c5b4'
Starting proxy for censored.com. Make sure to connect to localhost:25565 instead of the regular server address.
Server probably disconnected. Waiting for new connection...
java.lang.RuntimeException: Client not authenticated! 403: Forbidden
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:64)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmationWithProfileKey$7(EncryptionManager.java:247)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:120)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmationWithProfileKey(EncryptionManager.java:247)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:241)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:228)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:56)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
Server probably disconnected. Waiting for new connection...
Client probably disconnected. Waiting for new connection...   
...

```

**Version**
 - Game: Minecraft 1.19.1 / 1.19.2
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by SecretUser001** [comment]
Happened to me too. Did someone already find a solution?

**Comment by SecretUser001** [comment]
I have resolved my issue. I was using MultiMC, adding authentication to the world downloader solved the issue.
