### ISSUE TITLE
1.19.2 can't save world

### ISSUE THREAD

**Issue by polo1kani** [mircokroon/minecraft-world-downloader#443]
**Describe the bug**
minecraft 1.19.2 latest issue.
can not save world.
and Keep coming out error log.

**Steps to reproduce**
I don't use optifine or forge.
I use this downloader read by https://github.com/mircokroon/minecraft-world-downloader
useful 1.12 ~ 1.18
but 1.19 ~ 1.19.2 include issue.

**Log output**

#cmd
java -jar world-downloader.jar -s <server ad>

#log
Sep 15, 2022 9:12:35 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1bc6a36e'
Starting proxy for <server ad>. Make sure to connect to localhost:25565 instead of the regular server address.
Login success: <name> logged in with uuid <uuid>
Using protocol of game version 1.19 (760)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[6]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.DataTypeProvider.readInt(DataTypeProvider.java:80)
        at packets.handler.ClientBoundGamePacketHandler.lambda$new$16(ClientBoundGamePacketHandler.java:126)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
Can't (fully?) parse chunk at (0, 0, minecraft:overworld). Cause: Number of provided skylight maps does not match provided mask: {} != 64
java.lang.ArrayIndexOutOfBoundsException: Index 47 out of bounds for length 47
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:105)
        at packets.handler.version.ClientBoundGamePacketHandler_1_19.lambda$new$0(ClientBoundGamePacketHandler_1_19.java:42)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:105)
        at packets.handler.version.ClientBoundGamePacketHandler_1_19.lambda$new$1(ClientBoundGamePacketHandler_1_19.java:75)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:105)
        at packets.handler.version.ClientBoundGamePacketHandler_1_19.lambda$new$1(ClientBoundGamePacketHandler_1_19.java:75)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:105)
        at packets.handler.version.ClientBoundGamePacketHandler_1_19.lambda$new$1(ClientBoundGamePacketHandler_1_19.java:75)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:105)
        at packets.handler.version.ClientBoundGamePacketHandler_1_19.lambda$new$1(ClientBoundGamePacketHandler_1_19.java:75)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:105)
        at packets.handler.version.ClientBoundGamePacketHandler_1_19.lambda$new$1(ClientBoundGamePacketHandler_1_19.java:75)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
        at packets.DataTypeProvider.readString(DataTypeProvider.java:105)
        at packets.handler.version.ClientBoundGamePacketHandler_1_19.lambda$new$1(ClientBoundGamePacketHandler_1_19.java:75)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[3]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
        at packets.version.DataTypeProvider_1_14.readCoordinates(DataTypeProvider_1_14.java:13)
        at game.data.commandblock.CommandBlockManager.readAndStoreCommandBlock(CommandBlockManager.java:27)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$6(ServerBoundGamePacketHandler.java:73)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
        at game.data.entity.version.EquipmentReader_1_15.readSlots(EquipmentReader_1_15.java:19)
        at game.data.entity.Entity.addEquipment(Entity.java:175)
        at game.data.entity.EntityRegistry.lambda$addEquipment$14(EntityRegistry.java:171)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
        at game.data.entity.EntityRegistry.lambda$addEquipment$15(EntityRegistry.java:166)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[2]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:18)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
        at game.data.entity.version.EquipmentReader_1_15.readSlots(EquipmentReader_1_15.java:19)
        at game.data.entity.Entity.addEquipment(Entity.java:175)
        at game.data.entity.EntityRegistry.lambda$addEquipment$14(EntityRegistry.java:171)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
        at game.data.entity.EntityRegistry.lambda$addEquipment$15(EntityRegistry.java:166)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 29 out of bounds for byte[26]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.DataTypeProvider.readFloat(DataTypeProvider.java:208)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$1(ServerBoundGamePacketHandler.java:29)
        at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:38)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
        at game.data.entity.version.EquipmentReader_1_15.readSlots(EquipmentReader_1_15.java:19)
        at game.data.entity.Entity.addEquipment(Entity.java:175)
        at game.data.entity.EntityRegistry.lambda$addEquipment$14(EntityRegistry.java:171)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
        at game.data.entity.EntityRegistry.lambda$addEquipment$15(EntityRegistry.java:166)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

#repeat forever. Keep coming out error log

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: latest

**Comment by sheryxx** [comment]
Same issue here

**Comment by leovotapekcz** [comment]
same

**Comment by F3NXCorgi** [comment]
I had this issue, and it was resolved by using JDK 17, not 18.

**Comment by boomerboss** [comment]
Also have this issue, changing JDK not working for me either. Tried it in many different scenarios, simply not functional for 1.19 yet (I've been on 1.19.2 specifically)

**Comment by polo1kani** [comment]
thx bag fix.
