### ISSUE TITLE
Client not authenticated! 403: Forbidden (1.16.5-1.18.2) (Possibly ViaVerison)

### ISSUE THREAD

**Issue by lynrayy** [mircokroon/minecraft-world-downloader#447]
**Describe the bug**
An error occured Client not authenticated! 403: Forbidden

Possible problem: server using ViaVersion and it is possible to join server with 1.16-1.19

**Steps to reproduce**
1. Start WDL
2. Set up IP in wdl
3. RMB -> Pause chunk saving
4. Connected to server

**Log output**
```
java.lang.RuntimeException: Client not authenticated! 403: Forbidden
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:64)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$11(EncryptionManager.java:304)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:120)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:304)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:220)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:209)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:50)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)  
...

```
**Screenshots**
Can't log into server via WDL:
![image](https://i.imgur.com/mQNq77o.png)
Servers in server list: https://i.imgur.com/a0koF8w.png
Successfully logged into server directly: ![image](https://user-images.githubusercontent.com/59417884/192544710-a835769c-0f4d-40b7-b44e-890c15f43e62.png)

**Version**
 - Game: Minecraft 1.18.2
 - Also tested (same error): Minecraft 1.19.2
 - Also tested (same error): Minecraft 1.16.5
 - Downloader: latest (.jar)
 - Launcher (if login issues): PolyMC 1.4.1

**Comment by lynrayy** [comment]
Maybe it is because server disabled new microsoft reports feature

**Comment by lynrayy** [comment]
Trying 1.16.5:
`java.lang.RuntimeException: Client not authenticated! 403: Forbidden
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:64)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$11(EncryptionManager.java:304)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:120)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:304)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:220)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:209)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:50)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.IllegalStateException: Packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
	at packets.DataReader.readPackets(DataReader.java:172)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by mircokroon** [comment]
Probably this is due to the launcher you're using, so you'll have to use either a different launcher or use the Microsoft login option.
