### ISSUE TITLE
Wrong world loading

### ISSUE THREAD

**Issue by lynrayy** [mircokroon/minecraft-world-downloader#449]
**Describe the bug**
World loading in WLD incorrectly

**Steps to reproduce**
Pausing chunk loading
Going to NPC
Enabling chunk loading
Selecting SKYWARS
Me teleported to SKYWARS map
Map loading correctly in game
And looks like this in WDL
![image](https://user-images.githubusercontent.com/59417884/192617747-b10f4015-5bcb-4be6-ae49-b81a88f773a4.png)

**Log output**
```
Exception in thread "Chunk Parser Service" Exception in thread "Chunk Parser Service" java.lang.ArrayIndexOutOfBoundsException: Index 335 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:125)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:117)
	at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:113)
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:95)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:234)
	at game.data.chunk.ChunkImageFactory.recomputeHeight(ChunkImageFactory.java:276)
	at game.data.chunk.ChunkImageFactory.recomputeHeights(ChunkImageFactory.java:266)
	at game.data.chunk.version.Chunk_1_16.updateBlocks(Chunk_1_16.java:73)
	at game.data.WorldManager.lambda$multiBlockChange$6(WorldManager.java:684)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Chunk Parser Service" java.lang.ArrayIndexOutOfBoundsException: Index 339 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:125)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:117)
	at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:113)
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:95)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:234)
	at game.data.chunk.ChunkImageFactory.recomputeHeight(ChunkImageFactory.java:276)
	at game.data.chunk.ChunkImageFactory.recomputeHeights(ChunkImageFactory.java:266)
	at game.data.chunk.version.Chunk_1_16.updateBlocks(Chunk_1_16.java:73)
	at game.data.WorldManager.lambda$multiBlockChange$6(WorldManager.java:684)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: Index 340 out of bounds for length 256
	at game.data.chunk.version.encoder.BlockLocationEncoder_1_16.fetch(BlockLocationEncoder_1_16.java:19)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:125)
	at game.data.chunk.ChunkSection.getPaletteIndex(ChunkSection.java:117)
	at game.data.chunk.ChunkSection.getNumericBlockStateAt(ChunkSection.java:113)
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:95)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:234)
	at game.data.chunk.ChunkImageFactory.recomputeHeight(ChunkImageFactory.java:276)
	at game.data.chunk.ChunkImageFactory.recomputeHeights(ChunkImageFactory.java:266)
	at game.data.chunk.version.Chunk_1_16.updateBlocks(Chunk_1_16.java:73)
	at game.data.WorldManager.lambda$multiBlockChange$6(WorldManager.java:684)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Chunk Parser Service" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Chunk Parser Service" java.lang.ArrayIndexOutOfBoundsException


```
**Screenshots**
Result of WDL work:
![image](https://user-images.githubusercontent.com/59417884/192618049-4b9d50bc-76a5-4482-968e-6cd8e801fa28.png)
![image](https://user-images.githubusercontent.com/59417884/192618082-dfc6fce8-c34f-45db-ba89-dafa0a3e41e8.png)

**Version**
 - Game: Minecraft 1.18.1
 - Also tested (same result) Minecraft 1.18.2
 - Downloader: latest
 - Launcher (if login issues): PolyMC
 - Server: mineland (supports multiple minecraft versions, possibly viaversion)

**Comment by lynrayy** [comment]
How do I get around this bug: turn on resume chunk loading, die, fly away from the loading zone and fly back, loading the territory again
It is will better if WDL can forse load chunks again
