### ISSUE TITLE
Immediately throws error when trying to connect to localhost

### ISSUE THREAD

**Issue by Blackyyyyyy** [mircokroon/minecraft-world-downloader#470]
**Describe the bug**
I am using the .exe. I enter the IP and press start, i connect to localhost:number and it immediately throws error.

**Log output**
```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 2375 out of bounds for byte[29]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$0(ServerBoundLoginPacketHandler.java:28)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1589)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 1398 out of bounds for byte[261]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)         
...

```
**Version**
 - Game: Minecraft 1.19.3
 - Downloader: latest
 - Java 19 (no other versions installed)

**Comment by fatihb0y12** [comment]
i dont think 1.19.3 works i tried it so many times but it didnt work

**Comment by BSBMteam** [comment]
It doesn't work on 1.19.3

It started working after setting up 1.19.2 on Forge!  Authenticate your session with the instructions that tell you how to do it with PowerShell, this tutorial should be accessible from the app itself

**Comment by mircokroon** [comment]
1.19.3 is now supported on the latest version
