### ISSUE TITLE
Cannot download world data on servers with lobbies

### ISSUE THREAD

**Issue by DanGamingTV** [mircokroon/minecraft-world-downloader#474]
**Describe the bug**
Cannot download world data on servers with lobbies
The app can get the player's position, and register new chunks sent by the server, but no actual region data is shown or stored (No region folder created, no map is shown in the app - all chunks are black)

**Steps to reproduce**
Open and set up the app
Put in a server that has a lobby (I tried using play.loverfella.com)
Pause chunk saving
Log onto the localhost server
In the lobby, join the warp/subserver you want to join (I joined the megasurvival world)
Re-enable chunk saving
Try walking around

**Log output**
```
 java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1309)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:2405)
	at proxy.CompressionManager.zlibDecompress(CompressionManager.java:44)
	at proxy.CompressionManager.decompressPacket(CompressionManager.java:122)
	at packets.DataProvider.withSize(DataProvider.java:43)
	at packets.handler.PacketHandler.handle(PacketHandler.java:43)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at packets.handler.PacketHandler.handle(PacketHandler.java:49)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62) 

```
Full log: https://pastebin.com/Gkm47iww
**Screenshots**
![Screenshot 2023-01-05 015939](https://user-images.githubusercontent.com/36214413/210560452-75734d10-240a-4200-979a-ad2f4e2a292b.png)

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: latest
 - Launcher (if login issues): ?

**Comment by davelny** [comment]
Yeah same thing happened with me no idea how to fix it
