### ISSUE TITLE
1.19.3 support?

### ISSUE THREAD

**Issue by NormalHuman-Anything** [mircokroon/minecraft-world-downloader#478]
its not working and it just throws an error

**Comment by rautamiekka** [comment]
Nothing can be done if you don't type/paste the error as text (no screenshots).

**Comment by Kame03** [comment]
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 1977019 out of bounds for byte[25]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$0(ServerBoundLoginPacketHandler.java:28)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.security.InvalidKeyException: Key must not be null
        at java.base/sun.security.rsa.RSAKeyFactory.toRSAKey(RSAKeyFactory.java:120)
        at java.base/sun.security.rsa.RSASignature.engineInitVerify(RSASignature.java:94)
        at java.base/java.security.Signature$Delegate.tryOperation(Signature.java:1321)
        at java.base/java.security.Signature$Delegate.chooseProvider(Signature.java:1276)
        at java.base/java.security.Signature$Delegate.engineInitVerify(Signature.java:1349)
        at java.base/java.security.Signature.initVerify(Signature.java:506)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:231)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:228)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:56)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
Encryption failure! Terminating.

**Comment by NormalHuman-Anything** [comment]
that is the exact error I get

**Comment by WarpedStudios** [comment]
Sadly still support hasn't been added for 1.19.3 yet.

**Comment by Kame03** [comment]
Thank you :) Finally it came!
