### ISSUE TITLE
I have the latest java runtime but it still gives the mismatched version error on run

### ISSUE THREAD

**Issue by 8bit-coder** [mircokroon/minecraft-world-downloader#48]
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

```
Just gives that error even though I went to the java website and downloaded the latest java version. Am I doing something wrong?

**Comment by 8bit-coder** [comment]
Also maven doesn't appear to be a windows thing, any resources for compiling this on windows 10? I have the JDK of 14.0.2 and I have java 8 update 241(the latest version)

**Comment by 8bit-coder** [comment]
Nevermind, anyone also having the issue: Downloading the latest JDK ALSO downloads the latest JRE. Then just do a command like: 
"C:\Program Files\Java\jdk-14.0.2\bin\java.exe" -jar world-downloader.jar -s server.link.to.download
