### ISSUE TITLE
Null Point Exception when trying to downloaded modded world

### ISSUE THREAD

**Issue by Tow121** [mircokroon/minecraft-world-downloader#491]
**Describe the bug**
Short description of what the bug is: As soon as i load into a modded server, the world downloader straight up fails with a NULL POINT EXCEPTION. 

**Steps to reproduce**
If possible, describe how the bug can be achieved. 1. Go onto Curseforge and install the latest version of Antimatter Chemistry
2. Open the world downloader and start it after putting in: official-antimatter.g.akliz.net into the server address bar
**Log output**

java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4709)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4709)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

 java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null

 java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at se.llbit.nbt.StringTag.write(StringTag.java:57)
	at se.llbit.nbt.StringTag.write(StringTag.java:53)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.ListTag.write(ListTag.java:71)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at se.llbit.nbt.CompoundTag.write(CompoundTag.java:68)
	at se.llbit.nbt.NamedTag.write(NamedTag.java:70)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:63)
	at game.data.chunk.ChunkBinary.fromChunk(ChunkBinary.java:92)
	at game.data.region.Region.lambda$toFile$0(Region.java:142)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4709)
	at game.data.region.Region.toFile(Region.java:123)
	at game.data.WorldManager.save(WorldManager.java:421)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$2(WorldManager.java:398)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

 java.lang.NullPointerException ((it keeps going on with this last line))

**Screenshots**

**Version**
 - Game: Minecraft 1.12.2
 - Downloader: latest
 - Launcher (if login issues): N/A (no login issues)

**Comment by Tow121** [comment]
![image](https://user-images.githubusercontent.com/114936043/223218026-6106eba9-f005-4368-be89-1b32577081b0.png)
The problem isnt my Java version since i have java 19

**Comment by Godivctor** [comment]
i will add this
https://pastebin.com/TS1WzUmW

Version 1.7.10 forge
authentification with microsoft

logged to server and can play but nothing appear in the map
