### ISSUE TITLE
MWDL will crash with Netty error when a Forge or Fabric instance is used

### ISSUE THREAD

**Issue by Tsoccerguy3** [mircokroon/minecraft-world-downloader#494]
**Describe the bug**
When Minecraft is using a Forge of Fabric instance , the Minecraft client will not connect to the server though localhost . I suspect it has something to do with Forge and Fabric comminicate back and forth with dual channels while Vanilla uses 1 channel to the server . I tested your latest commit 779cad4bc569afb923f5fa31202c118eb7194c87 and MWDL crashes on connect to local host

**Steps to reproduce**
Create a Forge and a Fabric instance for 1.19.2 and 1.19.3 ( i think it will effect all Forge and Fabric versions. No mods are needed as this is the Netty engine of the game. 
Log into the Forge 1.19.2 or 3 instance start up MWDL set up a server , then star and start Localhost

**Log output**
[debug.log](https://github.com/mircokroon/minecraft-world-downloader/files/10934355/debug.log)

```
**Screenshots**

below



**Version**
 - Game: Minecraft All 
 - Downloader: All
 - Launcher (if login issues): All

**Comment by Tsoccerguy3** [comment]
![2023-03-09_12 41 34](https://user-images.githubusercontent.com/22108822/224111864-1b968542-8f0e-4cc7-ab19-8cd17021727f.png)

**Comment by Tsoccerguy3** [comment]
![2023-03-09_12 40 16](https://user-images.githubusercontent.com/22108822/224112127-cedd44e4-588b-4fac-b810-e29a93f5407e.png)

**Comment by mircokroon** [comment]
No log output at all from the downloader?

**Comment by Tsoccerguy3** [comment]
On the 1.19.3 WIP commit I tested today MWDL crashes the moment the Localhost is launched . I then tested the 1.65 MWDL here is the log from it

java.lang.RuntimeException: Client not authenticated! 403: Forbidden
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:64)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmationWithProfileKey$7(EncryptionManager.java:247)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:120)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmationWithProfileKey(EncryptionManager.java:247)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:241)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:228)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:56)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by Tsoccerguy3** [comment]
I tested with 1.17 version and MDWL crashed with no log using a Forge 1.19.2 instance of the client

It should be easy enough for you to install a 1.19.2 forge instance and run the Client , no mods needed . check MWDL with the Forge instance

**Comment by Tsoccerguy3** [comment]
I just tested version 1.17 with the Vanilla 1.19.2 client and MWDL crashes when you launch the localhost , no logs

**Comment by Tsoccerguy3** [comment]
The 1.165 version still works with Vanilla

**Comment by mircokroon** [comment]
Latest version doesn't support 1.19.2 anymore. Looks like Forge doesn't work with automatic authentication currently, so you will have to go to the Authentication tab and select "Microsoft login" most likely. 

I'll see if I can add some better signage for what's going wrong as it's currently fairly confusing for users to see where the issue is
