### ISSUE TITLE
Failed to get Credentials. [1.19]

### ISSUE THREAD

**Issue by KeineSecrets** [mircokroon/minecraft-world-downloader#503]
**Describe the bug**
Failed to get Credentials.

**Steps to reproduce**
1. Start Application
2. Enter Server-IP
3. Click on **Start**
4. Join the localhost

**Log output**
```
Could not get details from access token'. Status: 401
proxy.auth.MinecraftAuthenticationException: Cannot get profile.
	at proxy.auth.AuthDetails.update(AuthDetails.java:51)
	at proxy.auth.AuthDetails.getUuid(AuthDetails.java:117)
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:51)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$11(EncryptionManager.java:299)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:114)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:299)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:214)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Version**
 - Game: Minecraft 1.19.3 / 1.19.4
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
What authentication method are you using? e.g. maybe good to try Microsoft login instead of automatic

**Comment by KeineSecrets** [comment]
I did use every method, sometimes it works just fineAm 12.04.23, 12:33 schrieb mircokroon ***@***.***>:

   
  What authentication method are you using? e.g. maybe good to try Microsoft login instead of automatic

**Comment by KeineSecrets** [comment]
I did use every method, sometimes it works just fine

**Comment by SAPET123** [comment]
I am having this same issue but no matter what auth method I use none seem to work.
