### ISSUE TITLE
Chunks dont save

### ISSUE THREAD

**Issue by Fran12334** [mircokroon/minecraft-world-downloader#504]
**Describe the bug**
when trying to download a world the chunks dont get saved and my game crashes

**Steps to reproduce**
- '/usr/lib/jvm/java-18-openjdk-amd64/bin/java' -jar '/home/jogos/Transferências/world-downloader(1).jar' -s complementary.apexmc.co
- program opens
- start 
- mc crashes an chunks dont get saved
**Log output**
```
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.io.FileNotFoundException: /home/jogos/Transferências/cache/1_19_4/blocks.json (Ficheiro ou pasta inexistente)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at game.data.registries.RegistryLoader.generateGlobalPalette(RegistryLoader.java:205)
	at game.data.chunk.palette.GlobalPaletteProvider.requestPalette(GlobalPaletteProvider.java:46)
	at game.data.chunk.palette.GlobalPaletteProvider.getGlobalPalette(GlobalPaletteProvider.java:28)
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:95)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:269)
	at game.data.chunk.ChunkImageFactory.recomputeHeight(ChunkImageFactory.java:311)
	at game.data.chunk.ChunkImageFactory.updateHeight(ChunkImageFactory.java:288)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:512)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:486)
	at game.data.WorldManager.lambda$blockChange$8(WorldManager.java:643)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Chunk Parser Service" java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.GlobalPalette.getState(int)" because "globalPalette" is null
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:100)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:269)
	at game.data.chunk.ChunkImageFactory.recomputeHeight(ChunkImageFactory.java:311)
	at game.data.chunk.ChunkImageFactory.updateHeight(ChunkImageFactory.java:288)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:512)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:486)
	at game.data.WorldManager.lambda$blockChange$8(WorldManager.java:643)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.io.FileNotFoundException: /home/jogos/Transferências/cache/1_19_4/blocks.json (Ficheiro ou pasta inexistente)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at game.data.registries.RegistryLoader.generateGlobalPalette(RegistryLoader.java:205)
	at game.data.chunk.palette.GlobalPaletteProvider.requestPalette(GlobalPaletteProvider.java:46)
	at game.data.chunk.palette.GlobalPaletteProvider.getGlobalPalette(GlobalPaletteProvider.java:28)
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:95)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:269)
	at game.data.chunk.ChunkImageFactory.recomputeHeight(ChunkImageFactory.java:311)
	at game.data.chunk.ChunkImageFactory.updateHeight(ChunkImageFactory.java:288)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:512)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:486)
	at game.data.WorldManager.lambda$blockChange$8(WorldManager.java:643)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "Chunk Parser Service" java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.GlobalPalette.getState(int)" because "globalPalette" is null
	at game.data.chunk.ChunkSection.computeHeight(ChunkSection.java:100)
	at game.data.chunk.ChunkImageFactory.computeHeight(ChunkImageFactory.java:269)
	at game.data.chunk.ChunkImageFactory.recomputeHeight(ChunkImageFactory.java:311)
	at game.data.chunk.ChunkImageFactory.updateHeight(ChunkImageFactory.java:288)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:512)
	at game.data.chunk.Chunk.updateBlock(Chunk.java:486)
	at game.data.WorldManager.lambda$blockChange$8(WorldManager.java:643)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.io.FileNotFoundException: /home/jogos/Transferências/cache/1_19_4/blocks.json (Ficheiro ou pasta inexistente)

...
that is only part of it, but it just repeats things like that
```

**Version**
 - Game: Minecraft 1.19.4 (Quilt)
 - Downloader: 1.17.1

**Comment by mircokroon** [comment]
I would suggest deleting the `cache` folder and trying again, looks like something went wrong the first time you used the application
