### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Jumpy85Plays** [mircokroon/minecraft-world-downloader#510]
**Describe the bug**
Whenever i try to connect to localhost the world downloader crashes instantly. Currently using Minecraft 1.19.2 and was using it on a modded server.

**Steps to reproduce**
If possible, describe how the bug can be achieved.

**Log output**
```
n/a 
the world downloader app vanishes and Minecraft gives an cannot connect to server error.
...

```
**Screenshots**
![error](https://user-images.githubusercontent.com/114305760/231093276-e3d8b9cd-25df-4e91-8b9b-509574770208.png)

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: latest
 - Launcher (if login issues): No problems logging in

**Comment by Merded** [comment]
+1

**Comment by Merded** [comment]
+1
```
javax.crypto.BadPaddingException: Decryption error
        at java.base/sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:369)
        at java.base/sun.security.rsa.RSAPadding.unpad(RSAPadding.java:282)
        at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:372)
        at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:406)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:206)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
Encryption failure! Terminating.
```
