### ISSUE TITLE
SSLHandshake Error when using AdoptOpenJDK9 

### ISSUE THREAD

**Issue by huaji233333** [mircokroon/minecraft-world-downloader#52]
Here's my environment
```
$ ./java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)

$ uname -a
Linux  5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I ran the command below:
```
./java -jar '/$HOME/world-downloader.jar' -s server.ip
```
It worked properly first,but **errors occurred when downloading 'server.jar'** from [mojang](https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar).
```
Using protocol of game version 1.13.2 (404)
Looks like we have not run in version 1.13.2 before.
Downloading this version's server.jar (https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar)
Exception in thread "Thread-9" kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at kong.unirest.DefaultInterceptor.onFail(DefaultInterceptor.java:43)
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:133)
	at kong.unirest.BaseRequest.asBytes(BaseRequest.java:217)
	at game.data.RegistryLoader.downloadServerJar(RegistryLoader.java:95)
	at game.data.RegistryLoader.getReportsFromServerJar(RegistryLoader.java:82)
	at game.data.RegistryLoader.<init>(RegistryLoader.java:51)
	at game.Game.loadVersionRegistries(Game.java:164)
	at game.Game.lambda$getGameProtocol$0(Game.java:156)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
 ......
full output here https://paste.ubuntu.com/p/tpvkd442xh/
```
I have tried to run this on Windows10 with openjdk9, but had the same error.
What's more...The error was only appeard in openjdk9 .When I ran the .jar file **in openjdk 11 ,it worked properly** without any ssl errors. Could fix it or tell me what happened when using openjdk9?

**Comment by mircokroon** [comment]
I suggest you look online for issues related to `unable to find valid certification path to requested target`, such as [here](https://stackoverflow.com/questions/58705427/java-11-ssl-exception-unable-to-find-valid-certification-path-to-requested-targ). It seems like some sort of issue with the java installation rather than with the downloader.
