### ISSUE TITLE
I get this bug when joining 'localhost'

### ISSUE THREAD

**Issue by boriksim** [mircokroon/minecraft-world-downloader#520]
**Describe the bug**
The program starts as intented, I entered the IP of the server, but when joining 'localhost' in Minecraft, this error pops up

**Steps to reproduce**
If possible, describe how the bug can be achieved.

**Log output**

Apr 19, 2023 2:09:20 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @71e7a66b'
Starting proxy for mods.spworlds.org. Make sure to connect to localhost:25565 instead of the regular server address.
javax.crypto.BadPaddingException: Decryption error
        at java.base/sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:369)
        at java.base/sun.security.rsa.RSAPadding.unpad(RSAPadding.java:282)
        at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:366)
        at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:400)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2244)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:206)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Encryption failure! Terminating.

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: latest
 - Launcher (if login issues): CurseForge v.0.223.1.9730

**Comment by txmxthy** [comment]
https://github.com/mircokroon/minecraft-world-downloader/issues/534#issuecomment-1622189498
