### ISSUE TITLE
When connected to localhost the program cant authenticate my account and I will simply get disconnected from localhost.

### ISSUE THREAD

**Issue by HalinaPawlowska** [mircokroon/minecraft-world-downloader#522]
**Describe the bug**
When I turn on the world downloader jar and connect to a server through the localhost that he program gives me I simply get disconnected and I am greeted by this error in the settings tab: 

java.lang.RuntimeException: Client not authenticated! 403: Forbidden
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:64)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmationWithProfileKey$7(EncryptionManager.java:247)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:120)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmationWithProfileKey(EncryptionManager.java:247)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:241)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:107)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:228)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:56)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

I am using the automatic authentication but Ive tried the other ones too and none seem to be working. 

The program was working just fine yesterday and months prior to today so I have no clue what happened.

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: version [v1.16.5](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16.5)
 - Launcher (if login issues): Vanilla Minecraft launcher

Here is a video of me demostrating the issue: 

https://user-images.githubusercontent.com/132015888/234989111-5a193ab4-28db-48c8-a5e4-0631e351787a.mp4

**Comment by Meindo** [comment]
I had the same issue, fixed it by logging in on the downloader instead of leaving it on automatic.

**Comment by StrafeYourself** [comment]
oh ty, man but we have to long in every time :(

**Comment by StrafeYourself** [comment]
I am worried how could something like this just stop working.

**Comment by StrafeYourself** [comment]
Did he put a rat in it because he told me it was completely safe and he seems like a really nice guy.

**Comment by Meindo** [comment]
Why would he put a rat in it? Its open source, you could check the code and comipile it yourself if you want to

**Comment by Meindo** [comment]
About the not working part, i suspect its just due to microsoft updating their api or something, as multiple people seem to get this issue.

**Comment by StrafeYourself** [comment]
Yeah, sometimes open scouse does not always been it is safe but I think it is safe. Ahh, ok. Well thank you so much for helping understand mate. Also, I was wrong before we don't have to log in every time with the Microsoft authentication but for some reason now I do and I sadly don't know why man. Btw, tysm for all the amazing support :)

**Comment by StrafeYourself** [comment]
Wait, for some reason bro the chunks are not saving idk what on earth is going on but something aint right

**Comment by froggygroggy** [comment]
i have this same issue but i am logging in
