### ISSUE TITLE
World downloader crashes when i connect to it

### ISSUE THREAD

**Issue by 123321mario** [mircokroon/minecraft-world-downloader#53]
as soon i join the localhost server it crashes with this:

`Downloading this version's server.jar (https://launcher.mojang.com/v1/objects/a0d03225615ba897619220e256a266cb33a44b6b/server.jar)
java.nio.file.NoSuchFileException: cache\server.jar
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
        at java.base/java.nio.file.Files.write(Files.java:3491)
        at game.data.RegistryLoader.downloadServerJar(RegistryLoader.java:98)
        at game.data.RegistryLoader.getReportsFromServerJar(RegistryLoader.java:82)
        at game.data.RegistryLoader.<init>(RegistryLoader.java:51)
        at game.Game.loadVersionRegistries(Game.java:164)
        at game.Game.lambda$getGameProtocol$0(Game.java:156)
        at java.base/java.lang.Thread.run(Thread.java:832)`

i'm on win10 latest jre and jdk, MC 1.16.1

**Comment by mircokroon** [comment]
Does the downloader have writing permission for the current working directory? I suppose you could try running it in admin mode to ensure it does.
