### ISSUE TITLE
Encryption failure! Terminating.

### ISSUE THREAD

**Issue by undfndV** [mircokroon/minecraft-world-downloader#534]
**Describe the bug**
I wanted to copy the map to record replay modem, because the server render distance does not allow me to do so.
When joining the server I get an error and the program closes.

**Steps to reproduce**
Unfortunately, I do not know how this is possible and how this error can be achieved, although I can send a recording of what it looks like

**Log output**
```
C:\Users\user\Downloads>java -jar world-downloader.jar
com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @47d384ee'
Starting proxy for mc.endercrafted.pl. Make sure to connect to localhost:25565 instead of the regular server address.
Client probably disconnected. Waiting for new connection...
Client probably disconnected. Waiting for new connection...
javax.crypto.BadPaddingException: Decryption error
        at java.base/sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:369)
        at java.base/sun.security.rsa.RSAPadding.unpad(RSAPadding.java:282)
        at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:372)
        at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:406)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:206)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
Encryption failure! Terminating.
```

**Screenshots**
[Video unlisted on YouTube](https://youtu.be/h-ZauJuyTLE)

**Version**
 - Game: Minecraft 1.19.2
 - Downloader: latest
 - Launcher (if login issues): 2.4.79-1.2.4

**Comment by mircokroon** [comment]
Unfortunately 1.19.2 is not supported, if you want to download from that version you'll need an older release
https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.16.5
