### ISSUE TITLE
is 1.16.2 supported?

### ISSUE THREAD

**Issue by MNLegoBoy** [mircokroon/minecraft-world-downloader#54]
whenever I use it it gives this error multiple times, I am assuming this might be because I either did something wrong or 1.16.2 isn't supported yet.
java.lang.ArrayIndexOutOfBoundsException
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:79)
        at packets.DataTypeProvider.readInt(DataTypeProvider.java:69)
        at packets.builder.ClientBoundGamePacketBuilder.lambda$new$6(ClientBoundGamePacketBuilder.java:77)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:113)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:110)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.run(ProxyServer.java:68)

**Comment by mircokroon** [comment]
Looks like there were some changes in 1.16.2 that require a few small changes, so for now it's not supported. Hopefully in a week or so.

**Comment by mircokroon** [comment]
Now works in the [latest release](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.5.5)
