### ISSUE TITLE
Just getting disconnected?

### ISSUE THREAD

**Issue by Razzy52** [mircokroon/minecraft-world-downloader#553]
**Describe the bug**
Failed to connect to server disconnected

**Steps to reproduce**
If possible, describe how the bug can be achieved.

**Log output**
```
java.lang.RuntimeException: Server could not authenticate client! {}
	at proxy.auth.ServerAuthenticator.makeRequest(ServerAuthenticator.java:33)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$12(EncryptionManager.java:303)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:114)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:303)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:214)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1623)

```
**Screenshots**

**Version**
 - Game: Minecraft 1.20.1 Liquidbounce
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by TiAM0** [comment]
Having the same issue:

java.lang.RuntimeException: Client not authenticated! 403: Forbidden
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:65)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$11(EncryptionManager.java:299)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:114)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:299)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:214)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
Server probably disconnected. Waiting for new connection...
Client probably disconnected. Waiting for new connection...


"Client not authenticated! 403: Forbidden", but connecting to the same server without going via world-downloader works just fine.
