### ISSUE TITLE
Error while logging into local server

### ISSUE THREAD

**Issue by ww1150** [mircokroon/minecraft-world-downloader#56]
Login by: mjnoble
java.lang.NullPointerException
        at proxy.auth.LauncherProfiles.getAuthDetails(LauncherProfiles.java:17)
        at proxy.auth.ClientAuthenticator.getAuthDetails(ClientAuthenticator.java:139)
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:152)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$7(EncryptionManager.java:255)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:98)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:255)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:243)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:85)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:232)
        at packets.builder.ServerBoundLoginPacketBuilder.lambda$new$1(ServerBoundLoginPacketBuilder.java:28)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:93)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:90)
        at java.base/java.lang.Thread.run(Thread.java:832)
Client probably disconnected. Waiting for new connection...
WARNING: packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
Server probably disconnected. Waiting for new connection...

**Comment by Tragafantas** [comment]
But if its a local server why would you want to wdl?

**Comment by mircokroon** [comment]
Which game version is this?
