### ISSUE TITLE
Expired profile public key. Check that your system time is synchronized, and try restarting your game.

### ISSUE THREAD

**Issue by Jazz63540** [mircokroon/minecraft-world-downloader#588]
After running the world downloader, I have been softlocked out of 2b2t. Every time I try to join now, I get the message "Expired profile public key. Check that your system time is synchronized, and try restarting your game." Along with the error message on the world downloader below:

Log output
```
java.lang.NullPointerException: Cannot read field "parsingInProgress" because "parser" is null
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:135)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Chunk could not be parsed!

```

![image](https://github.com/mircokroon/minecraft-world-downloader/assets/22215605/04aff732-32a8-4016-939c-67936d747621)

**Version**
 - Game: Minecraft 1.19.4
 - Downloader: Latest

**Comment by mircokroon** [comment]
This is not related to the downloader, probably an issue with the server you're trying to join.

**Comment by Jazz63540** [comment]
> This is not related to the downloader, probably an issue with the server you're trying to join.

I was able to join 2b2t with no problems prior to using the world downloader. Surely something must have happened here
