### ISSUE TITLE
Client not authenticated! 403: Forbidden

### ISSUE THREAD

**Issue by TiAM0** [mircokroon/minecraft-world-downloader#593]
Hello,

Running latest 1.20.1 with

fabric-api-0.83.1+1.20.1.jar
lithium-fabric-mc1.20.1-0.11.2.jar
NoFog-1.3.4+1.16.5-1.20.1.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar

When connecting trough world-downloader the server says I'm not authenticated, when connecting directly to the server within the same session it works fine.

D:\wdtest>"C:\Program Files\Java\jdk-17.0.4.1\bin\java.exe" -jar world-downloader.jar -s TESTSERVER.COM --output D:\wdtest\worlddl
aug. 27, 2023 8:47:31 FM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6e3c1e69'
Starting proxy for TESTSERVER.COM. Make sure to connect to localhost:25565 instead of the regular server address.
Client probably disconnected. Waiting for new connection...
java.lang.RuntimeException: Client not authenticated! 403: Forbidden
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:65)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$11(EncryptionManager.java:299)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:114)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:299)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:214)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
        at java.base/java.lang.Thread.run(Thread.java:833)
Server probably disconnected. Waiting for new connection...
Client probably disconnected. Waiting for new connection...

**Comment by TiAM0** [comment]
Tried it without the mods and world-downloader works fine.

So seems to be an issue with the mods and world-downloader not working together.

Upgraded to latest mods including fabric loader 0.14.21 -> 0.14.22 wich I forgot to list above.

fabric-api-0.87.0+1.20.1.jar
sodium-fabric-mc1.20.1-0.5.2.jar

Still the same issue.

**Comment by mircokroon** [comment]
Automatic authentication doesn't always work, you'll have to use microsoft authentication or provide an auth token.

**Comment by TiAM0** [comment]
Thanks for the info. Figured it out, never tried the GUI before, only ever started it in cmdline and didn't see the options for it there or in docs.
