### ISSUE TITLE
EasyMC and The Altening support

### ISSUE THREAD

**Issue by lynrayy** [mircokroon/minecraft-world-downloader#605]
Please add support for EasyMC and The Altening (authentication). I'm trying to log in through those servers via meteor client but downloader
``` says java.lang.RuntimeException: Client not authenticated! 403: Forbidden
	at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:65)
	at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$11(EncryptionManager.java:299)
	at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:114)
	at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:299)
	at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:214)
	at proxy.EncryptionManager.attempt(EncryptionManager.java:101)
	at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:203)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:27)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by D-a-r-n-o-l-d** [comment]
don't add this, could get shut down by mojang.

**Comment by lynrayy** [comment]
don't listen DARNOLD
