### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Hello7809** [mircokroon/minecraft-world-downloader#607]
I downloaded the exe but when I run it didn't do anything but download the mod and create a log file (and yes, i have the latest version of java installed)

----------------------------------------------------------------------------------------------------------------------------
**Log output**

Trying to run java
	exit status 1
	Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
--------------------------------------------------------------------------------------------------------------------------
**Screenshots**

![Screenshot 2023-10-06 140651](https://github.com/mircokroon/minecraft-world-downloader/assets/147154830/d3d9e355-2da1-497a-836e-6441beb4c062)

**Comment by mircokroon** [comment]
Which version of Java do you have installed?

**Comment by rautamiekka** [comment]
You absolutely don't have the latest: 52.x is Java 8.x (of which you might have the latest), 61.x is Java 17.x.
