### ISSUE TITLE
"cannot find suitable Java version. Make sire one is correctly installed"

### ISSUE THREAD

**Issue by BSense-Code** [mircokroon/minecraft-world-downloader#611]
**Describe the bug**
I'm getting this error message everytime i try to connect to local host the world downloader crashes. I have java 21 and java 17 installed (see screenshot for location) but still get this error.

**Log output**
```
Trying to run java
	exit status 1
	Oct 23, 2023 11:10:31 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @d7b1517'
Application seems to be running without console. Redirecting error output to GUI. If this is not desired, run with --force-console.
Starting proxy for 149.56.176.143:25587. Make sure to connect to localhost:25565 instead of the regular server address.
Encryption failure! Terminating.

Trying to run C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\java.exe
	exit status 1
	Error: LinkageError occurred while loading main class Launcher
	java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

Trying to run C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\java.exe
	exit status 1
	Oct 23, 2023 11:11:09 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @694e1548'
Application seems to be running without console. Redirecting error output to GUI. If this is not desired, run with --force-console.
Starting proxy for 149.56.176.143:25587. Make sure to connect to localhost:25565 instead of the regular server address.
Encryption failure! Terminating.

Trying to run C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy\bin\java.exe
	exit status 1
	java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Trying to run C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64\bin\java.exe
	exit status 1
	java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"          
...

```
**Screenshots**
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/71489440/c097cc07-371d-45e2-9ce5-22f984414258)
![image](https://github.com/mircokroon/minecraft-world-downloader/assets/71489440/de04ced9-d21f-4ddf-bab2-bf3c533360dd)

**Version**
 - Game: Minecraft 1.19.2
 - Forge: 43.3.23
 - Downloader: latest

**Comment by KitsuTheFloof** [comment]
It is still not working.

**Comment by Xellero** [comment]
Does not work

**Comment by Davidos533** [comment]
Not working!

**Comment by eliazp05-ctrl** [comment]
dead issue, but i wanted to say that i have the same issue, a valid workaround is to download the .jar version and run it from cmd with `java -jar world-downloader.jar`
