### ISSUE TITLE
World Downloader bug

### ISSUE THREAD

**Issue by w2terx** [mircokroon/minecraft-world-downloader#633]
**Describe the bug**
It is not downloading the world once I enter it

**Steps to reproduce**
once I type the localhost:25565 and the launch the world, it says there is an error and to enter settings. That is where I get the error log

**Log output**
java.lang.ArrayIndexOutOfBoundsException: Index 19632 out of bounds for length 19632
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider$1.read(DataTypeProvider.java:198)
	at java.base/java.io.InputStream.read(InputStream.java:296)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:208)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:594)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550)
	at se.llbit.nbt.StringTag.read(StringTag.java:46)
	at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
	at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:195)
	at packets.handler.version.ClientBoundGamePacketHandler_1_18.lambda$new$1(ClientBoundGamePacketHandler_1_18.java:32)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.RuntimeException: VarInt is too big
	at packets.DataReader.readVarInt(DataReader.java:94)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[9]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:51)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Chunk could not be parsed!
        
...

```
**Screenshots**

![image](https://github.com/mircokroon/minecraft-world-downloader/assets/153954252/e4e9dee9-10d8-461d-b95c-ec522c356ba4)


**Version**
 - Game: Minecraft 1.20.2
 - Downloader: latest

**Comment by 99marvel** [comment]
If I'm not mistaken, this is just a bunch of gobbledygook that means 1.20.2 isn't supported yet. We will just have to wait patiently!

**Comment by ikonikisop** [comment]
So what version should we use?
