### ISSUE TITLE
Not able to download world

### ISSUE THREAD

**Issue by Mr-RS** [mircokroon/minecraft-world-downloader#641]
**Describe the bug**
Not able to download world in 1.20.4

**Steps to reproduce**
If possible, describe how the bug can be achieved.

**Log output**
java.lang.ArrayIndexOutOfBoundsException: Index 20 out of bounds for length 20
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider$1.read(DataTypeProvider.java:198)
	at java.base/java.io.InputStream.read(InputStream.java:293)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at se.llbit.nbt.StringTag.read(StringTag.java:46)
	at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
	at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:195)
	at packets.handler.version.ClientBoundGamePacketHandler_1_18.lambda$new$1(ClientBoundGamePacketHandler_1_18.java:32)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.entity.EntityRegistry.destroyEntities(EntityRegistry.java:187)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)

 	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]

 	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readLong(DataTypeProvider.java:155)
	at packets.DataTypeProvider.readUUID(DataTypeProvider.java:224)
	at game.data.entity.PlayerEntity.parse(PlayerEntity.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$6(EntityRegistry.java:88)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$addPlayer$7(EntityRegistry.java:86)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 11 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)

 java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.entity.EntityRegistry.destroyEntities(EntityRegistry.java:187)
	at packets.handler.ClientBoundGamePacketHandler.lambda$new$5(ClientBoundGamePacketHandler.java:60)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[9]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$2(ServerBoundGamePacketHandler.java:37)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Screenshots**

**Version**
 - Game: Minecraft 1.20.4
 - Downloader: latest
 - Launcher (if login issues): Latest

**Comment by SandwichBtw** [comment]
I'm having the same issue. I hope this can get fixed soon!

**Comment by heeaart** [comment]
same
