### ISSUE TITLE
Sleeping in 1.20.2 causes the client to crash

### ISSUE THREAD

**Issue by Booyahhayoob** [mircokroon/minecraft-world-downloader#649]
**Describe the bug**
Per title.

**Steps to reproduce**
Try to sleep in a bed. Watch your soul evidently leave your body as it gives the "sleeping" message but keeps you standing up, and the downloader says an error has occurred.

**Log output**
```
Exception in thread "Proxy" java.lang.Error: Cannot write an error tag to NBT stream (Unknown tag type: 0)
	at se.llbit.nbt.ErrorTag.tagType(ErrorTag.java:61)
	at game.data.chunk.ChunkEntities.addBlockEntity(ChunkEntities.java:142)
	at game.data.chunk.ChunkFactory.updateTileEntity(ChunkFactory.java:73)
	at packets.handler.version.ClientBoundGamePacketHandler_1_18.lambda$new$1(ClientBoundGamePacketHandler_1_18.java:37)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

```
**Screenshots**
![2024-02-09_08 27 28](https://github.com/mircokroon/minecraft-world-downloader/assets/23366241/966b3034-758f-42b1-bba2-d48017a057a4)

**Version**
 - Game: Minecraft 1.20.2
 - Downloader: latest

**Comment by urda** [comment]
This also occurs within `1.20.4` still.

**Comment by Laztec** [comment]
This also appears to happen when any other entities sleep, so flying over villages at night can be hazardous.
