### ISSUE TITLE
Unable to join server

### ISSUE THREAD

**Issue by akdude2000** [mircokroon/minecraft-world-downloader#653]
**Describe the bug**
throws error when trying to join after connecting to local host
**Steps to reproduce**
try to connect to a personal GTNH serverprogramm
you'd need to be white listed for that and I don't think they'd take kindly to this program as they woulden't even give a personal dimm file for use on a personal server.
**Log output**
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 6183 out of bounds for byte[172]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:92)
	at packets.handler.ClientBoundLoginPacketHandler.lambda$new$1(ClientBoundLoginPacketHandler.java:25)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 1284 out of bounds for byte[261]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:92)
	at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:26)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Screenshots**

**Version**
 - Game: Minecraft 1.7.10
 - Downloader: latest
on the greg tech new horizion pack

**Comment by exwundee** [comment]
I also receive the same issue using Minecraft 1.20.4.
