### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by enzomtpYT** [mircokroon/minecraft-world-downloader#68]
Hi im not english soo i don't understand the error can someone help me plz ?

Here is the logs : 
```
D:\Aquila\Desktop\enzomtp\World dl>java -jar world-downloader.jar -s eu.wynncraft.com
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

D:\Aquila\Desktop\enzomtp\World dl>pause
Appuyez sur une touche pour continuer...
```

**Comment by mircokroon** [comment]
Duplicatee of #29
