### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by xsvkaa** [mircokroon/minecraft-world-downloader#682]
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at game.data.dimension.DimensionCodec.readDimensions(DimensionCodec.java:90)
	at game.data.dimension.DimensionCodec.setDimensionNames(DimensionCodec.java:78)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_2.lambda$new$0(ClientBoundGamePacketHandler_1_20_2.java:35)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.RuntimeException: VarInt is too big

**Comment by xsvkaa** [comment]
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at game.data.dimension.DimensionCodec.readDimensions(DimensionCodec.java:90)
	at game.data.dimension.DimensionCodec.setDimensionNames(DimensionCodec.java:78)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_2.lambda$new$0(ClientBoundGamePacketHandler_1_20_2.java:35)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.RuntimeException: VarInt is too big

 java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
	at game.data.chunk.Chunk.getChunkSection(Chunk.java:65)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:104)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
	at game.data.chunk.Chunk.getChunkSection(Chunk.java:65)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_a1_18.java:104)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: Index 24 out of bounds for length 18
	at game.data.chunk.Chunk.getChunkSection(Chunk.java:65)
	at game.data.chunk.ChunkHeightHandler.computeHeight(ChunkHeightHandler.java:54)
	at game.data.chunk.ChunkHeightHandler.computeHeightMap(ChunkHeightHandler.java:34)
	at game.data.chunk.ChunkHeightHandler.<init>(ChunkHeightHandler.java:21)
	at game.data.chunk.Chunk.getChunkImageFactory(Chunk.java:488)
	at gui.GuiMap.setChunkLoaded(GuiMap.java:282)
	at gui.GuiManager.setChunkLoaded(GuiManager.java:347)
	at game.data.WorldManager.lambda$loadChunk$1(WorldManager.java:299)
	at game.data.chunk.Chunk.afterParse(Chunk.java:323)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:65)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
	at game.data.chunk.Chunk.getChunkSection(Chunk.java:65)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.ChunkHeightHandler.heightAt(int, int)" because the return value of "game.data.chunk.Chunk.getChunkHeightHandler()" is null
	at game.data.WorldManager.checkAboveSurface(WorldManager.java:194)
	at game.data.WorldManager.save(WorldManager.java:421)
	at game.data.WorldManager.save(WorldManager.java:467)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$3(WorldManager.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.ChunkHeightHandler.heightAt(int, int)" because the return value of "game.data.chunk.Chunk.getChunkHeightHandler()" is null
	at game.data.WorldManager.checkAboveSurface(WorldManager.java:194)
	at game.data.WorldManager.save(WorldManager.java:421)
	at game.data.WorldManager.save(WorldManager.java:467)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$3(WorldManager.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.ChunkHeightHandler.heightAt(int, int)" because the return value of "game.data.chunk.Chunk.getChunkHeightHandler()" is null
	at game.data.WorldManager.checkAboveSurface(WorldManager.java:194)
	at game.data.WorldManager.save(WorldManager.java:421)
	at game.data.WorldManager.save(WorldManager.java:467)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$3(WorldManager.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.ChunkHeightHandler.heightAt(int, int)" because the return value of "game.data.chunk.Chunk.getChunkHeightHandler()" is null
	at game.data.WorldManager.checkAboveSurface(WorldManager.java:194)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.ChunkHeightHandler.heightAt(int, int)" because the return value of "game.data.chunk.Chunk.getChunkHeightHandler()" is null
	at game.data.WorldManager.checkAboveSurface(WorldManager.java:194)
	at game.data.WorldManager.save(WorldManager.java:421)
	at game.data.WorldManager.save(WorldManager.java:467)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.WorldManager.lambda$start$3(WorldManager.java:417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
	at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
	at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:22)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.ChunkHeightHandler.heightAt(int, int)" because the return value of "game.data.chunk.Chunk.getChunkHeightHandler()" is null
