### ISSUE TITLE
Modded Support?

### ISSUE THREAD

**Issue by Mikemike110803** [mircokroon/minecraft-world-downloader#685]
Hi every time i try to copy a modded world i get a error and the world is either blank or have built
java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.BlockState.getName()" because "state" is null
	at game.data.chunk.version.Chunk_1_18.findBlockEntities(Chunk_1_18.java:145)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:131)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.BlockState.getName()" because "state" is null
	at game.data.chunk.version.Chunk_1_18.findBlockEntities(Chunk_1_18.java:145)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:131)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.BlockState.getName()" because "state" is null
	at game.data.chunk.version.Chunk_1_18.findBlockEntities(Chunk_1_18.java:145)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:131)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)

 	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)

 	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.State.toNbt()" because the return value of "game.data.chunk.palette.Registry.getState(int)" is null
	at game.data.chunk.palette.SingleValuePalette.toNbt(SingleValuePalette.java:65)
	at game.data.chunk.version.Chunk_1_18.containsBlockEntities(Chunk_1_18.java:156)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:130)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

 java.lang.NullPointerException: Cannot invoke "game.data.chunk.palette.BlockState.getName()" because "state" is null
	at game.data.chunk.version.Chunk_1_18.findBlockEntities(Chunk_1_18.java:145)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:131)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 	at game.data.chunk.version.Chunk_1_18.findBlockEntities(Chunk_1_18.java:145)
	at game.data.chunk.version.Chunk_1_18.readChunkColumn(Chunk_1_18.java:131)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:54)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:6

**Version**
 - Game: Minecraft 1.18.2
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
Modded worlds are generally not supported at this time unfortunately
