### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LM5610** [mircokroon/minecraft-world-downloader#687]
java.lang.NullPointerException: Cannot invoke "game.data.coordinates.CoordinateDouble3D.increment(double, double, double)" because "this.pos" is null
        at game.data.entity.PlayerEntity.incrementPosition(PlayerEntity.java:63)
        at game.data.entity.EntityRegistry.lambda$updatePositionRelative$12(EntityRegistry.java:178)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:22)
        at game.data.entity.EntityRegistry.lambda$updatePositionRelative$13(EntityRegistry.java:174)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        
        
        version: 1.20.4-paper

**Comment by zeppeliino** [comment]
same problem
