### ISSUE TITLE
"Client not authenticated!"

### ISSUE THREAD

**Issue by JYYYYYLim** [mircokroon/minecraft-world-downloader#69]
ran the executable via terminal, all valid switches set.
proxy (localhost) detected, unable to connect. d/ced after "encrypting" on loading screen.
doublechecked client token and login credentials, all of them fine
tried with different servers, not working as well

log:
java.lang.RuntimeException: Client not authenticated! {\
  "error" : "ForbiddenOperationException",\
  "path" : "/session/minecraft/join"\
}\
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:167)\
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$7(EncryptionManager.java:255)\
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:98)\
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:255)\
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:243)\
        at proxy.EncryptionManager.attempt(EncryptionManager.java:85)\
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:232)\
        at packets.builder.ServerBoundLoginPacketBuilder.lambda$new$1(ServerBoundLoginPacketBuilder.java:28)\
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)\
        at packets.DataReader.readPackets(DataReader.java:161)\
        at packets.DataReader.pushData(DataReader.java:116)\
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:93)\
        at proxy.ProxyServer.attempt(ProxyServer.java:138)\
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:90)\
        at java.base/java.lang.Thread.run(Unknown Source)\
Client probably disconnected. Waiting for new connection...\
Server probably disconnected. Waiting for new connection...

**Comment by ChillerDragon** [comment]
I could reproduce it with these steps:

1. login with account A in vanilla minecraft launcher to set the token in ~/.minecraft
2. logout with account A and close vanilla launcher
3. start world downloader without -m argument so it assumes  ~/.minecraft
4. connect with account B on localhost using multiMC

So @JYYYYYLim  is it possible that you have multiple accounts and multiple minecraft launchers?

**Comment by JYYYYYLim** [comment]
no, only 1 account. 
been transferred 1 time though, just putting this here since some say it causes jank
i also use tlauncher, had another launcher installed but uninstalled, never used it

args: -s (ip) --port (port)
using it on a private server yields this error. same goes when testing on uncensoredlibrary 
providing the directory manually with `-m` doesnt seem to do anything either

**Comment by ChillerDragon** [comment]
Oh I also realized sometimes order matters. If your launcher creates a new token on start make sure to first start minecraft and then the world downloader so it does not load an outdated token.

**Comment by JYYYYYLim** [comment]
order has already been accounted for, issue still unsolved
does directory contents affect verification by any chance?
or is this tested on any other launcher other than the standard minecraft launcher?

**Comment by ChillerDragon** [comment]
> or is this tested on any other launcher other than the standard minecraft launcher?

I use multiMC and it works fine

**Comment by mircokroon** [comment]
Have you tried using the manual authentication? I guess you could probably force it by running it with an invalid Minecraft path, so `-m wrongplace` for example.

**Comment by mircokroon** [comment]
No updates in a while and not reproducible (?) so I'll close this

**Comment by Bl4Cc4t** [comment]
I had this issue as well, solved it by using the token from the path of the launcher I actually use.
I use the Twitch client, so I navigated to `C:\Users\<username>\Twitch\Minecraft\Install` and used the token from there.

**Comment by JYYYYYLim** [comment]
ok so apparently its just jank in the profile file.
for tlauncher, just delete `launcher-profiles`, let it regenerate and use the token from there.

issue resolved
