### ISSUE TITLE
Not Working Current versions.

### ISSUE THREAD

**Issue by PurpleSquirtles** [mircokroon/minecraft-world-downloader#707]
Packet Reading Error 1.21.3

Running Latest version of software on 1.21.3 
Once connected provides the below.

**Log output**
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:112)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:238)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:21)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)

 java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)
	at packets.DataTypeProvider.readString(DataTypeProvider.java:127)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.commonInfo(ClientBoundGamePacketHandler_1_20_6.java:79)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$3(ClientBoundGamePacketHandler_1_20_6.java:70)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)
	at packets.DataTypeProvider.readString(DataTypeProvider.java:127)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.commonInfo(ClientBoundGamePacketHandler_1_20_6.java:79)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$3(ClientBoundGamePacketHandler_1_20_6.java:70)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)
	at packets.DataTypeProvider.readString(DataTypeProvider.java:127)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.commonInfo(ClientBoundGamePacketHandler_1_20_6.java:79)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$3(ClientBoundGamePacketHandler_1_20_6.java:70)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)
	at packets.DataTypeProvider.readString(DataTypeProvider.java:127)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.commonInfo(ClientBoundGamePacketHandler_1_20_6.java:79)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$3(ClientBoundGamePacketHandler_1_20_6.java:70)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)
	at packets.DataTypeProvider.readString(DataTypeProvider.java:127)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.commonInfo(ClientBoundGamePacketHandler_1_20_6.java:79)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$3(ClientBoundGamePacketHandler_1_20_6.java:70)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)
	at packets.DataTypeProvider.readString(DataTypeProvider.java:127)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.commonInfo(ClientBoundGamePacketHandler_1_20_6.java:79)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$3(ClientBoundGamePacketHandler_1_20_6.java:70)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:98)
	at packets.DataTypeProvider.readString(DataTypeProvider.java:127)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.commonInfo(ClientBoundGamePacketHandler_1_20_6.java:79)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$3(ClientBoundGamePacketHandler_1_20_6.java:70)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:112)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:238)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:21)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:112)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:238)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:21)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:112)

 java.lang.NegativeArraySizeException: -10
	at packets.DataTypeProvider.readStringArray(DataTypeProvider.java:297)
	at packets.handler.version.ClientBoundGamePacketHandler_1_20_6.lambda$new$2(ClientBoundGamePacketHandler_1_20_6.java:50)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[9]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:112)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:238)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:21)
	at packets.handler.PacketHandler.handle(PacketHandler.java:58)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.ArrayIndexOutOfBoundsException
java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:133)
	at game.data.chunk.version.Chunk_1_18.parse(Chunk_1_18.java:51)
	at game.data.chunk.ChunkFactory.parseChunk(ChunkFactory.java:127)
	at game.data.chunk.ChunkFactory.readChunkDataPacket(ChunkFactory.java:144)
	at game.data.chunk.ChunkFactory.parse(ChunkFactory.java:104)
	at game.data.chunk.ChunkFactory.lambda$addChunk$9(ChunkFactory.java:91)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Chunk could not be parsed!

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

 java.lang.ArrayIndexOutOfBoundsException

**Version**
 - Game: Minecraft 1.21.3
 - Downloader: latest

**Comment by Auvalon** [comment]
year on me 2 pls update :/

i have udpate java 17 21 and 23 not work for me

**Comment by justl00kingaround** [comment]
Same issue here for 1.21.3
