### ISSUE TITLE
llama inventory: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ChillerDragon** [mircokroon/minecraft-world-downloader#71]
When opening inventory on a llama with 6 slots filled with 6 full shulkers each.
Minecraft version 1.16.3

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 9 out of bounds for byte[7]
        at java.base/java.lang.System.arraycopy(Native Method)
        at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:81)
        at packets.DataTypeProvider.readInt(DataTypeProvider.java:71)
        at packets.builder.ClientBoundGamePacketBuilder.lambda$new$6(ClientBoundGamePacketBuilder.java:82)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$7(ProxyServer.java:113)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.lambda$run$9(ProxyServer.java:110)
        at proxy.ProxyServer.attempt(ProxyServer.java:138)
        at proxy.ProxyServer.run(ProxyServer.java:68)
```

**Comment by mircokroon** [comment]
Guess I should have tested with llamas. Thanks, I'll look into it.
