### ISSUE TITLE
proxy crashes after connecting with 1.13.2

### ISSUE THREAD

**Issue by daiiwulf** [mircokroon/minecraft-world-downloader#76]
using client version 1.13.2, server version 1.13.2, and latest available download of the app, i get the following error:

```
java.nio.file.NoSuchFileException: cache\generated\reports\registries.json
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:326)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
        at java.base/java.nio.file.Files.move(Files.java:1425)
        at game.data.registries.RegistryLoader.moveReports(RegistryLoader.java:128)
        at game.data.registries.RegistryLoader.getReportsFromServerJar(RegistryLoader.java:86)
        at game.data.registries.RegistryLoader.<init>(RegistryLoader.java:53)
        at game.Game.loadVersionRegistries(Game.java:164)
        at game.Game.lambda$getGameProtocol$0(Game.java:156)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

This error occurs after client has connected to the proxy, the proxy forwarded on to the server, client is rendering the world. The downloader app states :

```
Using protocol of game version 1.13.2 (404)
Looks like we have not run in version 1.13.2 before.
Downloading this version's server.jar (https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar)
We'll generate some reports now, this may take a minute.
Starting output of Minecraft server.jar:
=       =       =       =       =       =       =       =
[15:23:25] [main/INFO]: Starting provider: Block List
[15:23:25] [main/INFO]: Block List finished after 326 ms
[15:23:25] [main/INFO]: Starting provider: Item List
[15:23:25] [main/INFO]: Item List finished after 7 ms
[15:23:25] [main/INFO]: Starting provider: Command Syntax
[15:23:28] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, <uuid>]
[15:23:28] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:23:28] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:23:28] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, <uuid>]
[15:23:28] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:23:28] [main/INFO]: Loaded 0 recipes
[15:23:28] [main/INFO]: Loaded 0 advancements
[15:23:28] [main/INFO]: Command Syntax finished after 3377 ms
=       =       =       =       =       =       =       =
Completed generating reports!
```

The proxy stays online for a few seconds during this 'generating report' stage, and then closes after the crash above. note, i've removed a uuid string and replaced with <uuid> in the log above.

**Comment by mircokroon** [comment]
This was caused by 1.13.2 supporting the `blocks.json` registry file, but not the one for entities etc.
