### ISSUE TITLE
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 49 column 20 path $.selectedUser

### ISSUE THREAD

**Issue by XfedeX** [mircokroon/minecraft-world-downloader#84]
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 49 column 20 path $.selectedUser
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at proxy.auth.ClientAuthenticator.<init>(ClientAuthenticator.java:35)
        at proxy.EncryptionManager.<init>(EncryptionManager.java:54)
        at game.Game.startProxy(Game.java:130)
        at Launcher.main(Launcher.java:13)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 49 column 20 path $.selectedUser
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 8 more

```

**Comment by szalony9szymek** [comment]
uninstall your jre and than install [jre 10](https://www.oracle.com/java/technologies/java-archive-javase10-downloads.html) (you need a free acount to download it)
(Java SE Runtime Environment 10.0.2 for your os from the page)

**Comment by mircokroon** [comment]
This could also be related to using a different launcher maybe? Do you use the default launcher or a different one?

**Comment by XfedeX** [comment]
I use Shiginima Launcher, why?

**Comment by szalony9szymek** [comment]
so u need to use the official launcher or use manual authentication
