### ISSUE TITLE
Add a way to connect multiple clients

### ISSUE THREAD

**Issue by gatolocoses** [mircokroon/minecraft-world-downloader#88]
I am trying to map a big area of a server, and I have multiple accounts, it would be very useful if there was a way for me to connect 2 or 4 accounts at the same time 
This is not a bug it is a suggestion

**Comment by DrMoraschi** [comment]
If you have 2 or 4 accounts you can open 2 or 4 minecraft instances

**Comment by mircokroon** [comment]
I guess the easiest way to do this currently is to launch multiple instances of the downloader, and merge the worlds using [something like this](https://github.com/mircokroon/minecraft-world-merger)

**Comment by gatolocoses** [comment]
thx I will try but now i am receiving this error when i try to connect a single account
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because "this.selectedUser" is null
        at proxy.auth.LauncherProfiles.getAuthDetails(LauncherProfiles.java:17)
        at proxy.auth.ClientAuthenticator.getAuthDetails(ClientAuthenticator.java:169)
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:193)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$7(EncryptionManager.java:255)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:98)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:255)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$6(EncryptionManager.java:243)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:85)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:232)
        at packets.builder.ServerBoundLoginPacketBuilder.lambda$new$1(ServerBoundLoginPacketBuilder.java:28)
        at packets.builder.PacketBuilder.build(PacketBuilder.java:46)
        at packets.DataReader.readPackets(DataReader.java:161)
        at packets.DataReader.pushData(DataReader.java:116)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:100)
        at proxy.ProxyServer.attempt(ProxyServer.java:165)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:97)
        at java.base/java.lang.Thread.run(Thread.java:832)
I can not conect a single client right now :(

**Comment by gatolocoses** [comment]
it is very weird to be honest, I spent most of today trying to figure out why sometimes it works and sometimes it does not, 
here are some things i was able  to find but they don't make sense tbh 
I tried with 4 accounts in total but was almost never able to AUTH them, tried on regular client, twitch client, and multimc
with multimc i just gave an incorrect path for the token directory, and enter the token manually when requested, for some reason this only work with 2 of the 3 accounts I was testing, i tried erasing all my Minecraft and starting from scratch but nothing worked.
Anyway back to the original question, once i was able to put 1 account to walk and download I tried to do the suggestion on top with no success at all, from my testing once an account is connected no other account can be connected cause server does not even show(localhost) it stays pinging but never allows me to connect and nothing happens in cmd.

**Comment by mircokroon** [comment]
When using the default launcher, which version were you using? It should be under settings -> about in the launcher. 

You can indeed not use multiple accounts on the downloader at once, so to do this you'd have to use multiple instances of the downloader. Doing this on one device without manual authentication could definitely cause problems such as these. You would have to be very careful not to use the wrong token for the wrong account.

**Comment by mircokroon** [comment]
Hmm I get this myself too now, it's possible they changed the launcher again since the beta? I'll investigate.

**Comment by mircokroon** [comment]
It did indeed seem to be that, should be fixed in the latest version.

**Comment by maxsupermanhd** [comment]
Any news? Are multiple client connections working?

**Comment by mircokroon** [comment]
Nope, this requires quite a bit of refactoring to make work and I don't consider it to be very high priority. I'll get around to it eventually.
